### A Pluto.jl notebook ###
# v0.17.3

using Markdown
using InteractiveUtils

# ╔═╡ 5a80aeb6-70d4-11ec-360e-3d2969d4a911
begin
	using CalculusWithJulia
	using Plots
	using QuadGK
	using Unitful, UnitfulUS
	using Roots
	using SymPy
end

# ╔═╡ 5a80b212-70d4-11ec-22a3-8d7aec70513b
begin
	using CalculusWithJulia.WeaveSupport
	import PyPlot
	pyplot()
	import LinearAlgebra: norm
	
	nothing
end

# ╔═╡ 5a8a4782-70d4-11ec-2c3c-49b84058e2af
using PlutoUI

# ╔═╡ 5a8a475a-70d4-11ec-3d62-05e4dfa9447d
HTML("""
<div class="admonition info">
<a href="https://CalculusWithJulia.github.io">
<img src="https://raw.githubusercontent.com/jverzani/CalculusWithJulia.jl/master/CwJ/misc/logo.png" alt="Calculus with Julia" width="48" />
</a>
<span style="font-size:32px">Calculus With Julia</span>
</div>
""")


# ╔═╡ 5a80a77c-70d4-11ec-3e6e-8da4db53461e
md"""# Volumes by slicing
"""

# ╔═╡ 5a80a7ae-70d4-11ec-0d69-434c90bafd02
md"""This section uses these add-on packages:
"""

# ╔═╡ 5a80b244-70d4-11ec-182a-b3f691490dc4
md"""---
"""

# ╔═╡ 5a80cd74-70d4-11ec-2514-83f61d04e183
let
	imgfile = "figures/michelin-man.jpg"
	caption = """
	
	Hey Michelin Man, how much does that costume weigh?
	
	"""
	ImageFile(:integrals, imgfile, caption)
end

# ╔═╡ 5a80cda6-70d4-11ec-2fe5-6d4a22ff554a
md"""An ad for a summer job says work as the Michelin Man! Sounds promising, but how much will that costume weigh? A very hot summer may make walking around in a heavy costume quite uncomfortable.
"""

# ╔═╡ 5a80cdb8-70d4-11ec-1b01-35a16b8bba6d
md"""A back-of-the envelope calculation would start by
"""

# ╔═╡ 5a80cf40-70d4-11ec-01d7-0762bb0598a4
md"""  * Mentally separating out each "tire" and lining them up one by one.
  * Counting the number of "tires" (or rings), say $n$.
  * Estimating the radius for each tire, say $r_i$ for $1 \leq i \leq n$.
  * Estimating the height for each tire, say $h_i$ for $1 \leq i \leq n$
"""

# ╔═╡ 5a80cf54-70d4-11ec-35ab-fb5849b77b1b
md"""Then the volume would be found by adding:
"""

# ╔═╡ 5a80cf7c-70d4-11ec-1eb0-3f4aa986bb27
md"""```math
V = \pi \cdot r_1^2 \cdot h_1 + \pi \cdot r_2^2 \cdot h_2 + \cdot + \pi \cdot r_n^2 \cdot h_n.
```
"""

# ╔═╡ 5a80cf92-70d4-11ec-05a8-fd5eb62c0d48
md"""The weight would come by multiplying the volume by some appropriate density.
"""

# ╔═╡ 5a80cfa4-70d4-11ec-073e-797bd43c824e
md"""Looking at the sum though, we see the makings of an approximate integral. If the heights were to get infinitely small, we might expect this to approach something like $V=\int_a^b \pi r(h)^2  dh$.
"""

# ╔═╡ 5a80cfae-70d4-11ec-3927-4fbfeca3b170
md"""In fact, we have in general:
"""

# ╔═╡ 5a80d09e-70d4-11ec-207c-c77a70a60981
md"""> **Volume of a figure with a known cross section**: The volume of a solid with known cross-sectional area $A_{xc}(x)$ from $x=a$ to $x=b$ is given by
>
> $V = \int_a^b A_{xc}(x) dx.$
>
> This assumes $A_{xc}(x)$ is integrable.

"""

# ╔═╡ 5a80d0d0-70d4-11ec-3566-996e5804d025
md"""This formula is derived by approximating the volume by "slabs" with volume $A_{xc}(x) \Delta x$ and using the Riemann integral's definition to pass to the limit. The discs of the Michelin man are an example, where the cross-sectional area is just that of a circle, or $\pi r^2$.
"""

# ╔═╡ 5a80d102-70d4-11ec-1b38-01b8ee1ad5cb
md"""## Solids of revolution
"""

# ╔═╡ 5a80d170-70d4-11ec-101a-df659677ccd4
md"""We begin with some examples of a special class of solids - solids of revolution. These have an axis of symmetry from which the slabs are then just circular disks.
"""

# ╔═╡ 5a80d18c-70d4-11ec-3cc3-db036ce3870d
md"""Consider the volume contained in this glass, it will depend on the radius at different values of $x$:
"""

# ╔═╡ 5a80d6de-70d4-11ec-1242-351013343b87
let
	imgfile = "figures/integration-glass.jpg"
	caption = L"""
	
	A wine glass oriented so that it is seen as generated by revolving a
	curve about the $x$ axis. The radius of revolution varies as a function of $x$
	between about $0$ and $6.2$cm.
	
	"""
	ImageFile(:integrals, imgfile, caption)
end

# ╔═╡ 5a80d710-70d4-11ec-1e6a-036c31171614
md"""If $r(x)$ is the radius as a function of $x$, then the cross sectional area is $\pi r(x)^2$ so the volume is given by:
"""

# ╔═╡ 5a80d72c-70d4-11ec-1d3b-ed5b1cdba6d0
md"""```math
V = \int_a^b \pi r(x)^2 dx.
```
"""

# ╔═╡ 5a80e034-70d4-11ec-2aca-6fe24d823ab1
note(L"""

The formula is for a rotation around the $x$-axis, but can easily be generalized to rotating around any line (say the $y$-axis or $y=x$, ...) just by adjusting what $r(x)$ is taken to be.

""")

# ╔═╡ 5a80e07a-70d4-11ec-1d77-e53f0779686c
md"""For a numeric example, we consider the original Red [Solo](http://en.wikipedia.org/wiki/Red_Solo_Cup) Cup. The dimensions of the cup were basically: a top diameter of $d_1 = 3~ \frac{3}{4}$ inches, a bottom diameter of $d_0 = 2~ \frac{1}{2}$ inches and a height of $h = 4~ \frac{3}{4}$ inches.
"""

# ╔═╡ 5a80e08e-70d4-11ec-3808-39aac7b8788c
md"""The central axis is straight down. If we rotate the cup so this is the $x$-axis, then we can get
"""

# ╔═╡ 5a80e0a0-70d4-11ec-0024-711a75d53d72
md"""```math
r(x) = \frac{d_0}{2} + \frac{d_1/2 - d_0/2}{h}x = \frac{5}{4} + \frac{5}{38}x
```
"""

# ╔═╡ 5a80e0ac-70d4-11ec-1b1f-91d0cc084457
md"""The volume in cubic inches will be:
"""

# ╔═╡ 5a80e0c0-70d4-11ec-0c99-b37cc7a185e0
md"""```math
V = \int_0^h \pi r(x)^2 dx
```
"""

# ╔═╡ 5a80e0ca-70d4-11ec-1dba-fffa8d43ded8
md"""This is
"""

# ╔═╡ 5a80e822-70d4-11ec-1c48-1be591f4a609
begin
	d0, d1, h = 2.5, 3.75, 4.75
	r(x) = d0/2 + (d1/2 - d0/2)/h * x
	vol, _ = quadgk(x -> pi * r(x)^2, 0, h)
end

# ╔═╡ 5a80e868-70d4-11ec-21de-652ed5da027e
md"""So $36.9 \text{in}^3$. How many ounces is that? It is useful to know that 1 [gallon](http://en.wikipedia.org/wiki/Gallon) of water is defined as $231$ cubic inches, contains $128$ ounces, and weighs $8.34$ pounds.
"""

# ╔═╡ 5a80e872-70d4-11ec-33e4-e151638ffc59
md"""So our cup holds this many ounces:
"""

# ╔═╡ 5a810208-70d4-11ec-13c1-357f853c6f2e
ozs = vol / 231 * 128

# ╔═╡ 5a810262-70d4-11ec-38b7-f56dce178218
md"""Full it is about $20$ ounces, though this doesn't really account for the volume taken up by the bottom of the cup, etc.
"""

# ╔═╡ 5a810294-70d4-11ec-3d6a-8dac416d8db3
md"""If you are poor with units, `Julia` can provide some help through the `Unitful` package. Here the additional `UnitfulUS` package must also be included, as was done above, to access fluid ounces:
"""

# ╔═╡ 5a810726-70d4-11ec-2c9e-c147f6f989c1
vol * u"inch"^3 |> us"floz"

# ╔═╡ 5a810758-70d4-11ec-1fe8-0d553f9c8a58
md"""Before Solo "squared" the cup, the Solo cup had markings that - [some thought](http://www.snopes.com/food/prepare/solocups.asp) - indicated certain volume amounts.
"""

# ╔═╡ 5a810bfe-70d4-11ec-234c-1544614cfc26
let
	imgfile = "figures/red-solo-cup.jpg"
	caption = "Markings on the red Solo cup indicated various volumes"
	ImageFile(:integrals, imgfile, caption)
end

# ╔═╡ 5a810c30-70d4-11ec-05fa-3b6da15c7d77
md"""What is the height for $5$ ounces (for a glass of wine)? $12$ ounces (for a beer unit)?
"""

# ╔═╡ 5a810c4e-70d4-11ec-3af1-5bd0713bcbf0
md"""Here the volume is fixed, but the height is not. For $v$ ounces, we need to convert to cubic inches. The conversion is $1$ ounce is $231/128 \text{in}^3$.
"""

# ╔═╡ 5a810c6c-70d4-11ec-3e29-691f0683f783
md"""So we need to solve $v \cdot (231/128) = \int_0^h\pi r(x)^2 dx$ for $h$ when $v=5$ and $v=12$.
"""

# ╔═╡ 5a810c80-70d4-11ec-2d13-03e7d847ebc6
md"""Let's express volume as a function of $h$:
"""

# ╔═╡ 5a8112fc-70d4-11ec-0f99-dfc491446a32
Vol(h) = quadgk(x -> pi * r(x)^2, 0, h)[1]

# ╔═╡ 5a811310-70d4-11ec-3f91-2549c9d0adee
md"""Then to solve we have:
"""

# ╔═╡ 5a8116f0-70d4-11ec-187a-f5f7f42597f1
begin
	v₅ = 5
	h5 = find_zero(h -> Vol(h) - v₅ * 231 / 128, 4)
end

# ╔═╡ 5a811702-70d4-11ec-12ae-8dc42b8ef3b0
md"""and
"""

# ╔═╡ 5a811aa4-70d4-11ec-22e3-af5d2576416f
begin
	v₁₂ = 12
	h12 = find_zero(h -> Vol(h) - v₁₂ * 231 / 128, 4)
end

# ╔═╡ 5a811ac2-70d4-11ec-30b5-215cbe9c170c
md"""As a percentage of the total height, these are:
"""

# ╔═╡ 5a811d2e-70d4-11ec-168b-69314f93f6e7
h5/h, h12/h

# ╔═╡ 5a813e58-70d4-11ec-32cb-113386096bd6
note("""
Were performance at issue, Newton's method might also have been considered here, as the derivative is easily computed by the fundamental theorem of calculus.
""")

# ╔═╡ 5a813ea8-70d4-11ec-373f-8362e1b2a7cb
md"""##### Example
"""

# ╔═╡ 5a813f02-70d4-11ec-36e3-efe81fba63a8
md"""By rotating the line segment $x/r + y/h=1$ that sits in the first quadrant around the $y$ axis, we will generate a right-circular cone. The volume of which can be expressed through the above formula by noting the radius, as a function of $y$, will be $R = r(1 - y/h)$. This gives the well-known volume of a cone:
"""

# ╔═╡ 5a814434-70d4-11ec-3e80-89cdd5a87d4a
let
	@syms r h x y
	R = r*(1 - y/h)
	integrate(pi*R^2, (y, 0, h))
end

# ╔═╡ 5a814466-70d4-11ec-06aa-cd2a20daaf12
md"""The frustum of a cone is simply viewed as a cone with its top cut off. If the original height would have been $h_0$ and the actual height $h_1$, then the volume remaining is just $\int_{h_0}^h \pi r(y)^2 dy = \pi h_1 r^2/3 - \pi h_0 r^2/3 = \pi r^2 (h_1-h_0)/3$.
"""

# ╔═╡ 5a814484-70d4-11ec-2e5c-e54a743c7254
md"""It is not unusual to parameterize a cone by the angle $\theta$ it makes and the height. Since $r/h=\tan\theta$, this gives the formula $V = \pi/3\cdot h^3\tan(\theta)^2$.
"""

# ╔═╡ 5a814498-70d4-11ec-374c-f1aa8ea41eab
md"""##### Example
"""

# ╔═╡ 5a87e410-70d4-11ec-1deb-85d353b8bcbf
md"""[Gabriel's](http://tinyurl.com/8a6ygv) horn is a geometric figure of mathematics - but not the real world - which has infinite height, but not volume! The figure is found by rotating the curve $y=1/x$ around the $x$ axis from $1$ to $\infty$. If the volume formula holds, what is the volume of this "horn?"
"""

# ╔═╡ 5a87f0e0-70d4-11ec-2694-85f9ce344a79
begin
	radius(x) = 1/x
	quadgk(x -> pi*radius(x)^2, 1, Inf)[1]
end

# ╔═╡ 5a87f16c-70d4-11ec-2138-417c4b065543
md"""That is a value very reminiscent of $\pi$, which it is as $\int_1^\infty 1/x^2 dx = -1/x\big|_1^\infty=1$.
"""

# ╔═╡ 5a88bc64-70d4-11ec-26bd-9bed32b448eb
note("""

The interest in this figure is that soon we will be able to show that
it has **infinite** surface area, leading to the
[paradox](http://tinyurl.com/osawwqm) that it seems possible to fill
it with paint, but not paint the outside.

""")

# ╔═╡ 5a88bcfa-70d4-11ec-3a85-150c79432b3a
md"""##### Example
"""

# ╔═╡ 5a88bd68-70d4-11ec-2d2f-15b092c15aee
md"""A movie studio hand is asked to find a prop vase to be used as a [Ming vase](http://en.wikipedia.org/wiki/Chinese_ceramics) in an upcoming scene. The dimensions specified are for the outside diameter in centimeters and are given by
"""

# ╔═╡ 5a88bda6-70d4-11ec-1b28-bfdab99a82af
md"""```math
d(h) = \begin{cases}
2 \sqrt{26^2 - (h-20)^2} & 0 \leq h \leq 44\\
20 \cdot e^{-(h - 44)/10} & 44 < h \leq 50.
\end{cases}
```
"""

# ╔═╡ 5a88bdc2-70d4-11ec-3a9d-e9c46404467a
md"""If the vase were solid, what would be the volume?
"""

# ╔═╡ 5a88be4e-70d4-11ec-2785-27d09cab3e32
md"""We define `d` using a ternary operator to handle the two cases:
"""

# ╔═╡ 5a88dab4-70d4-11ec-0562-7d7aa3ce82ef
begin
	d(h) = h <= 44 ? 2*sqrt(26^2 - (h-20)^2) : 20 * exp(-(h-44)/10)
	rad(h) = d(h)/2
end

# ╔═╡ 5a88db2a-70d4-11ec-37e2-6b2972a4bfc9
md"""The volume in cm$^3$ is then:
"""

# ╔═╡ 5a88e220-70d4-11ec-3332-97896066acb4
Vₜ, _ = quadgk(h -> pi * rad(h)^2, 0, 50)

# ╔═╡ 5a88e252-70d4-11ec-0079-f9889348c4af
md"""For the actual shoot, the vase is to be filled with ash, to simulate a funeral urn. (It will then be knocked over in a humorous manner, of course.) How much ash is needed if the vase has walls that are 1/2 centimeter thick
"""

# ╔═╡ 5a88e28e-70d4-11ec-0f22-430b69a6c8d2
md"""We need to subtract $0.5$ from the radius and `a` then recompute:
"""

# ╔═╡ 5a8900cc-70d4-11ec-17a6-01010d946dc8
V_int, _ = quadgk(h -> pi * (rad(h) - 1/2)^2, 1/2, 50)

# ╔═╡ 5a890124-70d4-11ec-0a59-670a52a1bd13
md"""A liter of volume is $1000 \text{cm}^3$. So this is about $68$ liters, or more than 15 gallons. Perhaps the dimensions given were bit off.
"""

# ╔═╡ 5a890142-70d4-11ec-23d3-355e7832185e
md"""While we are here, to compute the actual volume of the material in the vase could be done by subtraction.
"""

# ╔═╡ 5a890318-70d4-11ec-0099-61fa93307220
Vₜ - V_int

# ╔═╡ 5a890386-70d4-11ec-111c-2f4b5d82d390
md"""### The washer method
"""

# ╔═╡ 5a8903c2-70d4-11ec-14da-478119301b98
md"""Returning to the Michelin Man, in our initial back-of-the-envelope calculation we didn't account for the fact that a tire isn't a disc, as it has its center cut out. Returning, suppose $R_i$ is the outer radius and $r_i$ the inner radius. Then each tire has volume
"""

# ╔═╡ 5a8903ea-70d4-11ec-1c85-f13a8ded61ee
md"""```math
\pi R_i^2 h_i - \pi r_i^2 h_i = \pi (R_i^2 - r_i^2) h_i.
```
"""

# ╔═╡ 5a890412-70d4-11ec-35c4-2b72a5116e0d
md"""Rather than use $\pi r(x)^2$ for a cross section, we would use $\pi (R(x)^2 - r(x)^2)$.
"""

# ╔═╡ 5a891d76-70d4-11ec-332f-b302756d45f1
md"""In general we call a shape like the tire a "washer" and use this formula for a washer's cross section $A_{xc}(x) = \pi(R(x)^2 - r(x)^2)$.
"""

# ╔═╡ 5a891dbe-70d4-11ec-3c0c-5be5068df621
md"""Then the volume for the solid of revolution whose cross sections are washers would be:
"""

# ╔═╡ 5a891dec-70d4-11ec-119d-f99e65bef145
md"""```math
V = \int_a^b \pi \cdot (R(x)^2 - r(x)^2) dx.
```
"""

# ╔═╡ 5a891e16-70d4-11ec-3666-bf98bf7be010
md"""##### Example
"""

# ╔═╡ 5a891e50-70d4-11ec-180f-5548bbcf7631
md"""An artist is working with a half-sphere of material, and wishes to bore out a conical shape. What would be the resulting volume, if the two figures are modeled by
"""

# ╔═╡ 5a891e70-70d4-11ec-102f-fbbd1b948134
md"""```math
R(x) = \sqrt{1^2 - (x-1)^2}, \quad r(x) = x,
```
"""

# ╔═╡ 5a891eb6-70d4-11ec-2431-8baa61f3ba2b
md"""with $x$ ranging from $x=0$ to $1$?
"""

# ╔═╡ 5a891eca-70d4-11ec-36db-b1813968eb3d
md"""The answer comes by integrating:
"""

# ╔═╡ 5a89332e-70d4-11ec-01db-7ff2fb8dc93a
let
	Rad(x) = sqrt(1 - (x-1)^2)
	rad(x) = x
	V, _ = quadgk(x -> pi*(Rad(x)^2 - rad(x)^2), 0, 1)
end

# ╔═╡ 5a89337e-70d4-11ec-1ec5-b5029998610b
md"""## Solids with known cross section
"""

# ╔═╡ 5a893400-70d4-11ec-2b45-67d9d99830bb
md"""The Dart cup company now produces the red solo cup with a [square](http://www.solocup.com/products/squared-plastic-cup/) cross section. Suppose the dimensions are the same: a top diameter of $d_1 = 3 3/4$ inches, a bottom diameter of $d_0 = 2 1/2$ inches and a height of $h = 4 3/4$ inches. What is the volume now?
"""

# ╔═╡ 5a893432-70d4-11ec-1d50-6736693a7662
md"""The difference, of course, is that cross sections now have area $d^2$, as opposed to $\pi r^2$. This leads to some difference, which we quantify, as follows:
"""

# ╔═╡ 5a893d56-70d4-11ec-23bc-1f7375cb1852
let
	d0, d1, h = 2.5, 3.75, 4.75
	d(x) = d0 + (d1 - d0)/h * x
	vol, _ = quadgk(x -> d(x)^2, 0, h)
	vol / 231 * 128
end

# ╔═╡ 5a893d92-70d4-11ec-15e2-937fe48648a1
md"""This shape would have more volume - the cross sections are bigger. Presumably the dimensions have changed. Without going out and buying a cup, let's assume the cross-sectional diameter remained the same, not the diameter. This means the largest dimension is the same. The cross section diameter is $\sqrt{2}$ larger. What would this do to the area?
"""

# ╔═╡ 5a893dce-70d4-11ec-1f93-cb5cc79dd777
md"""We could do this two ways: divide $d_0$ and $d_1$ by $\sqrt{2}$ and recompute. However, each cross section of this narrower cup would simply be $\sqrt{2}^2$ smaller, so the total volume would change by $2$, or be 13 ounces. We have $26.04$ is too big, and $13.02$ is too small, so some other overall dimensions are used.
"""

# ╔═╡ 5a893e0a-70d4-11ec-1e79-8175db1450a3
md"""##### Example
"""

# ╔═╡ 5a893e32-70d4-11ec-0b15-77dab3633b55
md"""For a general cone, we use this [definition](http://en.wikipedia.org/wiki/Cone):
"""

# ╔═╡ 5a893f48-70d4-11ec-105e-09f34e208e23
md"""> A cone is the solid figure bounded by a base in a plane and by a surface (called the lateral surface) formed by the locus of all straight line segments joining the apex to the perimeter of the base.

"""

# ╔═╡ 5a893f72-70d4-11ec-2d8e-233208278594
md"""Let $h$ be the distance from the apex to the base. Consider cones with the property that all planes parallel to the base intersect the cone with the same shape, though perhaps a different scale. This figure shows an example, with the rays coming from the apex defining the volume.
"""

# ╔═╡ 5a894c56-70d4-11ec-2f17-c3dc3f4f3fef
let
	h = 5
	R, r, rho = 1, 1/4, 1/4
	f(t) = (R-r) * cos(t) + rho * cos((R-r)/r * t)
	g(t) = (R-r) * sin(t) - rho * sin((R-r)/r * t)
	ts = range(0, 2pi, length=100)
	
	p = plot(f.(ts), g.(ts), zero.(ts), legend=false)
	for t ∈ range(0, 2pi, length=25)
	    plot!(p, [0,f(t)], [0,g(t)], [h, 0], linecolor=:red)
	end
	p
end

# ╔═╡ 5a894cb0-70d4-11ec-17fe-651da3e91c68
md"""A right circular cone is one where this shape is a circle. This definition can be more general, as a square-based right pyramid is also such a cone. After possibly reorienting the cone in space so the base is at $u=0$ and the apex at $u=h$ the volume of the cone can be found from:
"""

# ╔═╡ 5a894ce2-70d4-11ec-21ae-b17f6f4a65ff
md"""```math
V = \int_0^h A_{xc}(u) du.
```
"""

# ╔═╡ 5a894d1e-70d4-11ec-0fd1-635114017f4d
md"""The cross sectional area $A_{xc}(u)$ satisfies a formula in terms of $A_{xc}(0)$, the area of the base:
"""

# ╔═╡ 5a894d3c-70d4-11ec-0a57-f59b334de963
md"""```math
A_{xc}(u)  = A_{xc}(0) \cdot (1 - \frac{u}{h})^2
```
"""

# ╔═╡ 5a894d50-70d4-11ec-2d89-17068cd19093
md"""So the integral becomes:
"""

# ╔═╡ 5a894d6e-70d4-11ec-23b2-65c03c02bbac
md"""```math
V = \int_0^h A_{xc}(u) du = A_{xc}(0) \int_0^h (1 - \frac{u}{h})^2 du = A_{xc}(0) \int_0^1 v^2 \frac{1}{h} dv = A_{xc}(0) \frac{h}{3}.
```
"""

# ╔═╡ 5a894d82-70d4-11ec-32a8-477aa4bd4dae
md"""This gives a general formula for the volume of such cones.
"""

# ╔═╡ 5a894db4-70d4-11ec-2fe3-35e110bf4f2c
md"""### Cavalieri's method
"""

# ╔═╡ 5a894df0-70d4-11ec-3ee3-7be18aadd86d
md"""[Cavalieri's](http://tinyurl.com/oda9xd9) Principle is "Suppose two regions in three-space (solids) are included between two parallel planes. If every plane parallel to these two planes intersects both regions in cross-sections of equal area, then the two regions have equal volumes." (Wikipedia).
"""

# ╔═╡ 5a894e2a-70d4-11ec-3a8b-817b8ae8a7b1
md"""With the formula for the volume of solids based on cross sections, this is a trivial observation, as the functions giving the cross-sectional area are identical. Still, it can be surprising. Consider a sphere with an interior cylinder bored out of it.  (The [Napkin](http://tinyurl.com/o237v83) ring problem.) The bore has height $h$ - for larger radius spheres this means very wide bores.
"""

# ╔═╡ 5a8965e2-70d4-11ec-3604-336607e92c5c
let
	#The following illustrates $R=5$ and $h=8$.
	
	R =5; h1 = 2*4
	
	theta = asin(h1/2/R)
	thetas = range(-theta, stop=theta, length=100)
	ts = range(-pi, stop=pi, length=100)
	y = h1/4
	
	p = plot(legend=false, aspect_ratio=:equal);
	plot!(p, R*cos.(ts), R*sin.(ts));
	plot!(p, R*cos.(thetas), R*sin.(thetas), color=:orange);
	
	plot!(p, [R*cos.(theta), R*cos.(theta)], [h1/2, -h1/2], color=:orange);
	plot!(p, [R*cos.(theta), sqrt(R^2 - y^2)], [y, y], color=:orange)
	
	plot!(p, [0, R*cos.(theta)], [0,0], color=:red);
	plot!(p,[ 0, R*cos.(theta)], [0,h1/2], color=:red);
	
	annotate!(p, [(.5, -2/3, "sqrt(R²- (h/2)²)"),
	              (R*cos.(theta)-.6, h1/4, "h/2"),
	              (1.5, 1.75*tan.(theta), "R")])
	
	p
end

# ╔═╡ 5a896652-70d4-11ec-3569-a147a8e6bfec
md"""The small orange line is rotated, so using the washer method we get the cross sections given by $\pi(r_0^2 - r_i^2)$, the outer and inner radii, as a function of $y$.
"""

# ╔═╡ 5a89668c-70d4-11ec-210e-819687c5310d
md"""The outer radii has points $(x,y)$ satisfying $x^2 + y^2 = R^2$, so is $\sqrt{R^2 - y^2}$. The inner radii has a constant value, and as indicated in the figure, is $\sqrt{R^2 - (h/2)^2}$, by the Pythagorean theorem.
"""

# ╔═╡ 5a8966aa-70d4-11ec-051d-433499bc06da
md"""Thus the cross sectional area is
"""

# ╔═╡ 5a89674a-70d4-11ec-3344-cf58ab82248a
md"""```math
\pi( (\sqrt{R^2 - y^2})^2 - (\sqrt{R^2 - (h/2)^2})^2 )
= \pi ((R^2 - y^2) - (R^2 - (h/2)^2))
= \pi ((\frac{h}{2})^2 - y^2)
```
"""

# ╔═╡ 5a89677c-70d4-11ec-116e-910a1a90635e
md"""As this does not depend on $R$, and the limits of integration would always be $-h/2$ to $h/2$ by Cavalieri's principle, the volume of the solid will be independent of $R$ too.
"""

# ╔═╡ 5a8967ae-70d4-11ec-0148-b937ad738a17
md"""To actually compute this volume, we take $R=h/2$, so that the bore hole is just a line of no volume, the resulting volume is then that of a sphere with radius $h/2$, or $4/3\pi(h/2)^3 = \pi h^3/6$.
"""

# ╔═╡ 5a8967f4-70d4-11ec-3ae8-5b96d985383e
md"""## The second theorem of Pappus
"""

# ╔═╡ 5a896844-70d4-11ec-1959-b53148e2e052
md"""The second theorem of [Pappus](http://tinyurl.com/l43vw4) says that if a plane figure $F$ is rotated around an axis to form a solid of revolution, the total volume can be written as $2\pi r A(F)$, where $r$ is the distance the centroid is from the axis of revolution, and $A(F)$ is the area of the plane figure. In short, the distance traveled by the centroid times the area.
"""

# ╔═╡ 5a89688a-70d4-11ec-15b1-39e76b40c410
md"""This can make some computations trivial. For example, we can make a torus (or donut) by rotating the circle $(x-2)^2 + y^2 = 1$ about the $y$ axis. As the centroid is clearly $(2, 0)$, with $r=2$ in the above formula, and the area of the circle is $\pi 1^2$, the volume of the donut is $2\pi(2)(\pi) = 4\pi^2$.
"""

# ╔═╡ 5a8968b2-70d4-11ec-002c-87fbe9d11f79
md"""##### Example
"""

# ╔═╡ 5a896916-70d4-11ec-3e7a-c1626f29c713
md"""Above, we found the volume of a cone, as it is a solid of revolution, through the general formula. However, parameterizing the cone as the revolution of a triangle with vertices $(0,0)$, $(r, 0)$, and $(0,h)$ and using the formula for the center of mass in the $x$ direction of such a triangle, $r/3$, we get that the volume of a cone with height $h$ and radius $r$ is  $2\pi (r/3)\cdot (rh/2) = \pi r^2 h/3$, in agreement with the calculus based computation.
"""

# ╔═╡ 5a896934-70d4-11ec-3ab3-8dd48f7b8a01
md"""## Questions
"""

# ╔═╡ 5a89698e-70d4-11ec-24ca-cf5c71a1e938
md"""###### Question
"""

# ╔═╡ 5a8969ac-70d4-11ec-10fa-f91f280edb62
md"""Consider this big Solo cup:
"""

# ╔═╡ 5a896f42-70d4-11ec-3c75-d58bcac7fd86
let
	imgfile ="figures/big-solo-cup.jpg"
	caption = " Big solo cup. "
	ImageFile(:integrals, imgfile, caption)
end

# ╔═╡ 5a896f7e-70d4-11ec-3d9b-e953c44c82e9
md"""It has approximate dimensions: smaller radius 5 feet, upper radius 8 feet and height 15 feet. How many gallons is it? At $8$ pounds a gallon this would be pretty heavy!
"""

# ╔═╡ 5a896fb0-70d4-11ec-267e-6ddecc497196
md"""Two facts are useful:
"""

# ╔═╡ 5a8970e6-70d4-11ec-1352-dda5609ce426
md"""  * a cubic foot is 7.48052 gallons
  * the radius as a function of height is $r(h) = 5  + (3/15)\cdot h$
"""

# ╔═╡ 5a899602-70d4-11ec-0b28-8b53904570ac
let
	gft = 7.48052
	rad(h) = 5 + (3/15)*h
	a,err = quadgk(h -> pi*rad(h)^2, 0, 15)
	val = a*gft
	numericq(val, 1e1)
end

# ╔═╡ 5a899670-70d4-11ec-282e-d71d3e9e3a0d
md"""###### Question
"""

# ╔═╡ 5a89971a-70d4-11ec-03bb-035f2c7c4402
md"""In *Glass Shape Influences Consumption Rate* for Alcoholic [Beverages](http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0043007) the authors demonstrate that the shape of the glass can have an effect on the rate of consumption, presumably people drink faster when they aren't sure how much they have left. In particular, they comment that people have difficulty judging the half-finished-by-volume mark.
"""

# ╔═╡ 5a899742-70d4-11ec-3e05-f36514390651
md"""This figure shows some of the wide variety of beer-serving glasses:
"""

# ╔═╡ 5a899f3a-70d4-11ec-03a3-53843366b36d
let
	imgfile ="figures/beer_glasses.jpg"
	caption = "A variety of different serving glasses for beer."
	ImageFile(:integrals, imgfile, caption)
end

# ╔═╡ 5a899fda-70d4-11ec-2b8b-a9ff1b50a50d
md"""We work with metric units, as there is a natural relation between volume in cm$^3$ and liquid measure ($1$ liter = $1000$ cm$^3$, so a $16$-oz pint glass is roughly $450$ cm$^3$.)
"""

# ╔═╡ 5a89a004-70d4-11ec-167f-091ecc9d8a41
md"""Let two glasses be given as follows. A typical pint glass with linearly increasing radius:
"""

# ╔═╡ 5a89a052-70d4-11ec-04bb-f72484021900
md"""```math
r(h) = 3 + \frac{1}{5}h, \quad 0 \leq h \leq b;
```
"""

# ╔═╡ 5a89a070-70d4-11ec-27f0-9918f4048bfe
md"""and a curved-edge one:
"""

# ╔═╡ 5a89a096-70d4-11ec-23a7-a55cdad4930a
md"""```math
s(h) = 3 + \log(1 + h), \quad 0 \leq h \leq b
```
"""

# ╔═╡ 5a89a0c0-70d4-11ec-27be-7f8f5ffaaeb5
md"""The following functions find the volume as a function of height, $h$:
"""

# ╔═╡ 5a89a8a2-70d4-11ec-2a41-31e351fc27b5
begin
	r1(h) = 3 + h/5
	s1(h) = 2 + log(1 + h)
	r_vol(h) = quadgk(x -> pi*r1(x)^2, 0, h)[1]
	s_vol(h) = quadgk(x -> pi*s1(x)^2, 0, h)[1]
end

# ╔═╡ 5a89a9b2-70d4-11ec-28d2-7162aeeb8067
md"""  * For the straight-sided glass find $h$ so that the volume is $450$.
"""

# ╔═╡ 5a89b29a-70d4-11ec-2c27-f156923d8b43
begin
	h450 = find_zero(h -> r_vol(h) - 450, 10)
	numericq(h450)
end

# ╔═╡ 5a89b416-70d4-11ec-04e4-d3f778f263b8
md"""  * For the straight-sided glass find $h$ so that the volume is $225$ (half full).
"""

# ╔═╡ 5a89bdda-70d4-11ec-0f54-b3c9662bc1c9
begin
	h225 = find_zero(h -> r_vol(h) - 225, 10)
	numericq(h225)
end

# ╔═╡ 5a89be8c-70d4-11ec-3f31-5bd74e22000e
md"""  * For the straight-sided glass, what is the percentage of the total height when the glass is half full. (For a cylinder it would just be 50.
"""

# ╔═╡ 5a89c6c2-70d4-11ec-2468-8d58cba3945b
numericq(h225/450 * 100, 2, units="percent")

# ╔═╡ 5a89c794-70d4-11ec-36d0-7dab59c6b02a
md"""  * People often confuse the half-way by height amount for the half way by volume, as it is for the cylinder. Take the height for the straight-sided glass filled with $450$ mm, divide it by $2$, then compute the percentage of volume at the half way height to the original.
"""

# ╔═╡ 5a89d0a2-70d4-11ec-2998-a1a5cf13c624
numericq(r_vol(h450/2)/450*100, 2, units="percent")

# ╔═╡ 5a89d0e0-70d4-11ec-0f39-1325e28a6a9a
md"""---
"""

# ╔═╡ 5a89d16c-70d4-11ec-2d9f-abf165d818d1
md"""  * For the curved-sided glass find $h$ so that the volume is $450$.
"""

# ╔═╡ 5a89db1e-70d4-11ec-1f1f-1166c42a572e
begin
	h_450 = find_zero(h -> s_vol(h) - 450, 10)
	numericq(h_450)
end

# ╔═╡ 5a89dbb0-70d4-11ec-03ed-cd222e32832e
md"""  * For the curved-sided glass find $h$ so that the volume is $225$ (half full).
"""

# ╔═╡ 5a89e242-70d4-11ec-2c1c-bf5089221c6d
begin
	h_225 = find_zero(h -> s_vol(h) - 225, 10)
	numericq(h_225)
end

# ╔═╡ 5a89e2e2-70d4-11ec-1725-33e13859ea0b
md"""  * For the curved-sided glass, what is the percentage of the total height when the glass is half full. (For a cylinder it would just be 50.
"""

# ╔═╡ 5a89e80a-70d4-11ec-3a4c-410f47245611
numericq(h_225/450 * 100, 2, units="percent")

# ╔═╡ 5a89e88c-70d4-11ec-256c-3f495811cc7e
md"""  * People often confuse the half-way by height amount for the half way by volume, as it is for the cylinder. Take the height for the curved-sided glass filled with $450$ mm, divide it by $2$, then compute the percentage of volume at the half way height to the original.
"""

# ╔═╡ 5a89ef30-70d4-11ec-186a-d1f7af7e4230
numericq(s_vol(h_450/2)/450*100, 2, units="percent")

# ╔═╡ 5a89ef6e-70d4-11ec-346b-fd73c6713d20
md"""###### Question
"""

# ╔═╡ 5a89efb2-70d4-11ec-3790-7b4c81a0b222
md"""A right [pyramid](http://en.wikipedia.org/wiki/Pyramid_%28geometry%29) has its apex (top point) above the centroid of its base, and for our purposes, each of its cross sections. Suppose a pyramid has square base of dimension $w$ and height of dimension $h$.
"""

# ╔═╡ 5a89efbc-70d4-11ec-3a4b-47f66634b235
md"""Will this integral give the volume:
"""

# ╔═╡ 5a89efce-70d4-11ec-3e18-33002c7c5195
md"""```math
V = \int_0^h w^2 (1 - \frac{y}{h})^2 dy?
```
"""

# ╔═╡ 5a89f296-70d4-11ec-282c-5f9d90667707
let
	yesnoq("yes")
end

# ╔═╡ 5a89f2aa-70d4-11ec-13de-8790066331dc
md"""What is the volume?
"""

# ╔═╡ 5a8a130c-70d4-11ec-3340-59741685d6c8
let
	choices = [
	"``1/3 \\cdot b\\cdot h``",
	"``1/3 \\cdot w^2\\cdot h``",
	"``l\\cdot w \\cdot h/ 3``"
	]
	ans = 2
	radioq(choices, ans)
end

# ╔═╡ 5a8a1336-70d4-11ec-0b2d-754fe3cde64a
md"""###### Question
"""

# ╔═╡ 5a8a1370-70d4-11ec-3f94-b79a6fdc88e0
md"""An ellipsoid is formed by rotating the region in the first and second quadrants bounded by the ellipse $(x/2)^2 + (y/3)^2=1$ and the $x$ axis around the $x$ axis. What is the volume of this ellipsoid? Find it numerically.
"""

# ╔═╡ 5a8a1b22-70d4-11ec-0b03-1b27fbb530c3
let
	f(x) = 3*sqrt( 1 - (x/2)^2 )
	val, _ = quadgk(x -> pi * f(x)^2, -2, 2)
	numericq(val)
end

# ╔═╡ 5a8a1b42-70d4-11ec-040d-b3641511ed11
md"""###### Question
"""

# ╔═╡ 5a8a1b68-70d4-11ec-1fe7-11eff37b220c
md"""An ellipsoid is formed by rotating the region in the first and second quadrants bounded by the ellipse $(x/a)^2 + (y/b)^2=1$ and the $x$ axis around the $x$ axis. What is the volume of this ellipsoid? Find it symbolically.
"""

# ╔═╡ 5a8a22b6-70d4-11ec-02b9-99adaaa7954d
let
	choices = [
	"``4/3 \\cdot \\pi a b^2``",
	"``4/3 \\cdot \\pi a^2 b``",
	"``\\pi/3 \\cdot a b^2``"
	]
	ans = 1
	radioq(choices, ans)
end

# ╔═╡ 5a8a22d4-70d4-11ec-2057-e77b2792034d
md"""###### Question
"""

# ╔═╡ 5a8a22fc-70d4-11ec-1e8f-cf4c11fbe99f
md"""A solid is generated by rotating the region enclosed by the graph $y=\sqrt{x}$, the lines $x=1$, $x=2$, and $y=1$ about the $x$ axis. Find the volume of the solid.
"""

# ╔═╡ 5a8a26a8-70d4-11ec-10b2-61da8893aa89
let
	Ra(x) = sqrt(x)
	ra(x) = 1
	a,b=1,2
	val, _ = quadgk(x -> pi * (Ra(x)^2 - ra(x)^2), a,b)
	numericq(val)
end

# ╔═╡ 5a8a26bc-70d4-11ec-13c0-8d58799ac82f
md"""###### Question
"""

# ╔═╡ 5a8a26da-70d4-11ec-218c-197c7a9bc864
md"""The region enclosed by the graphs of $y=x^3 - 1$ and $y=x-1$ are rotated around the $y$ axis. What is the volume of the solid?
"""

# ╔═╡ 5a8a29fa-70d4-11ec-0d43-f7909d7b2ea6
let
	@syms x
	plot(x^3 - 1, 0, 1, legend=false)
	plot!(x-1)
end

# ╔═╡ 5a8a2e96-70d4-11ec-3d39-c181d62c9b77
let
	Ra(y) = cbrt(y+1)
	ra(y) = y + 1
	a,b = 0, 1
	val, _ = quadgk(x -> pi * (Ra(x)^2 - ra(x)^2), a,b)
	numericq(val)
end

# ╔═╡ 5a8a2eb4-70d4-11ec-23f0-a99bc01424bc
md"""###### Question
"""

# ╔═╡ 5a8a2edc-70d4-11ec-3d05-5b6fa29b97bf
md"""Rotate the region bounded by $y=e^x$, the line $x=\log(2)$ and the first quadrant about the line $x=\log(2)$.
"""

# ╔═╡ 5a8a2eee-70d4-11ec-2a6d-1b9bbac446ea
md"""(Be careful, the radius in the formula $V=\int_a^b \pi r(u)^2 du$ is from the line $x=\log(2)$.)
"""

# ╔═╡ 5a8a3404-70d4-11ec-3e77-97130b87d085
let
	a, b = 0, exp(log(2))
	ra(y) = log(2) - log(y)
	val, _ = quadgk(y -> pi * ra(y)^2, a, b)
	numericq(val)
end

# ╔═╡ 5a8a3422-70d4-11ec-05a0-b7c12c32ecf7
md"""###### Question
"""

# ╔═╡ 5a8a344a-70d4-11ec-2de9-89c4dce3b1ef
md"""Find the volume of rotating the region bounded by the line $y=x$, $x=1$ and the $x$-axis around the line $y=x$. (The Theorem of Pappus is convenient and the fact that the centroid of the triangular region lies at $(2/3, 1/3)$.)
"""

# ╔═╡ 5a8a39ae-70d4-11ec-11c2-69a382ecd97e
let
	cm=[2/3, 1/3]
	c = [1/2, 1/2]
	r = norm(cm - c)
	A = 1/2 * 1 * 1
	val = 2pi*r*A
	numericq(val)
end

# ╔═╡ 5a8a39ca-70d4-11ec-1ff7-9fd242575e24
md"""###### Question
"""

# ╔═╡ 5a8a39ea-70d4-11ec-25dc-a7cf62c8eaed
md"""Rotate the region bounded by the line $y=x$ and the function $f(x) = x^2$ about the line $y=x$. What is the resulting volume?
"""

# ╔═╡ 5a8a3a12-70d4-11ec-07a4-3396ba09fb93
md"""You can integrate in the length along the line $y=x$ ($u$ from $0$ to $\sqrt{2}$). The radius then can be found by intersecting the line perpendicular line to $y=x$ at $u$ to the curve $f(x)$. This will do so:
"""

# ╔═╡ 5a8a3e22-70d4-11ec-13de-cb5ddf461ceb
begin
	theta = pi/4  ## we write y=x as y = x * tan(pi/4) for more generality, as this allows other slants.
	
	f(x) = x^2
	𝒙(u) = find_zero(x -> u*sin(theta) - 1/tan(theta) * (x - u*cos(theta)) - f(x), (u*cos(theta), 1))
	𝒓(u) = sqrt((u*cos(theta) - 𝒙(u))^2 + (u*sin(theta) - f(𝒙(u)))^2)
end

# ╔═╡ 5a8a3e4a-70d4-11ec-0b9f-c58092d10d3a
md"""(Though in this case you can also find `r(u)` using the quadratic formula.)
"""

# ╔═╡ 5a8a3e54-70d4-11ec-1aab-7fd3f8e10ddc
md"""With this, find the volume.
"""

# ╔═╡ 5a8a42aa-70d4-11ec-11fe-ad1c7df684cf
let
	a, b = 0, sqrt(2)
	val, _ = quadgk(u -> pi*𝒓(u)^2, a, b)
	numericq(val)
end

# ╔═╡ 5a8a42be-70d4-11ec-0427-0122c70ebb29
md"""---
"""

# ╔═╡ 5a8a42de-70d4-11ec-1f3c-119e7e7d000a
md"""Repeat (find the volume) only this time with the function $f(x) = x^{20}$.
"""

# ╔═╡ 5a8a4750-70d4-11ec-20e7-45c106f45cff
let
	a, b = 0, sqrt(2)
	f(x) = x^20
	xval(u) = find_zero(x -> u*sin(theta) - 1/tan(theta) * (x - u*cos(theta)) - f(x), (0,sqrt(2)))
	rad(u) = sqrt((u*cos(theta) - xval(u))^2 + (u*sin(theta) - f(xval(u)))^2)
	val, _ = quadgk(u -> pi*rad(u)^2, a, b)
	numericq(val)
end

# ╔═╡ 5a8a477a-70d4-11ec-255a-e14677a1f335
HTML("""<div class="markdown"><blockquote>
<p><a href="../integrals/center_of_mass.html">◅ previous</a>  <a href="../integrals/arc_length.html">▻  next</a>  <a href="../index.html">⌂ table of contents</a>  <a href="https://github.com/jverzani/CalculusWithJulia.jl/edit/master/CwJ/integrals/volumes_slice.jmd">✏ suggest an edit</a></p>
</blockquote>
</div>""")

# ╔═╡ 5a8a478c-70d4-11ec-1d89-076996d20f5c
PlutoUI.TableOfContents()

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulUS = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"

[compat]
CalculusWithJulia = "~0.0.13"
Plots = "~1.25.4"
PlutoUI = "~0.7.29"
PyPlot = "~2.10.0"
QuadGK = "~2.4.2"
Roots = "~1.3.14"
SymPy = "~1.1.2"
Unitful = "~1.10.1"
UnitfulUS = "~0.2.0"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.0"
manifest_format = "2.0"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "8eaf9f1b4921132a4cff3f36a1d9ba923b14a481"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.1.4"

[[deps.Adapt]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "af92965fb30777147966f58acb05da51c5616b5f"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "3.3.3"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[deps.ArrayInterface]]
deps = ["Compat", "IfElse", "LinearAlgebra", "Requires", "SparseArrays", "Static"]
git-tree-sha1 = "1ee88c4c76caa995a885dc2f22a5d548dfbbc0ba"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "3.2.2"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "19a35467a82e236ff51bc17a3a44b69ef35185a2"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.8+0"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "4b859a208b2397a7a623a03449e4636bdb17bcf2"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.1+1"

[[deps.CalculusWithJulia]]
deps = ["Base64", "Contour", "EllipsisNotation", "ForwardDiff", "HCubature", "IntervalSets", "JSON", "LaTeXStrings", "LinearAlgebra", "Markdown", "Mustache", "Pkg", "PlotUtils", "Random", "RecipesBase", "Reexport", "Requires", "Roots", "SpecialFunctions", "Test"]
git-tree-sha1 = "ae958b53cc06c6b3d5d5b0847a3d858075136417"
uuid = "a2e0e22d-7d4c-5312-9169-8b992201a882"
version = "0.0.13"

[[deps.ChainRulesCore]]
deps = ["Compat", "LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "926870acb6cbcf029396f2f2de030282b6bc1941"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "1.11.4"

[[deps.ChangesOfVariables]]
deps = ["ChainRulesCore", "LinearAlgebra", "Test"]
git-tree-sha1 = "bf98fa45a0a4cee295de98d4c1462be26345b9a1"
uuid = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
version = "0.1.2"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "Random"]
git-tree-sha1 = "a851fec56cb73cfdf43762999ec72eff5b86882a"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.15.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "024fe24d83e4a5bf5fc80501a314ce0d1aa35597"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.0"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "417b0ed7b8b838aa6ca0a87aadf1bb9eb111ce40"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.8"

[[deps.Combinatorics]]
git-tree-sha1 = "08c8b6831dc00bfea825826be0bc8336fc369860"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.2"

[[deps.CommonEq]]
git-tree-sha1 = "d1beba82ceee6dc0fce8cb6b80bf600bbde66381"
uuid = "3709ef60-1bee-4518-9f2f-acd86f176c50"
version = "0.2.0"

[[deps.CommonSolve]]
git-tree-sha1 = "68a0743f578349ada8bc911a5cbd5a2ef6ed6d1f"
uuid = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
version = "0.2.0"

[[deps.CommonSubexpressions]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "7b8a93dba8af7e3b42fecabf646260105ac373f7"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.3.0"

[[deps.Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "SHA", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "44c37b4636bc54afac5c574d2d02b625349d6582"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "3.41.0"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"

[[deps.Conda]]
deps = ["Downloads", "JSON", "VersionParsing"]
git-tree-sha1 = "6cdc8832ba11c7695f494c9d9a1c31e90959ce0f"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.6.0"

[[deps.ConstructionBase]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "f74e9d5388b8620b4cee35d4c5a618dd4dc547f4"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.3.0"

[[deps.Contour]]
deps = ["StaticArrays"]
git-tree-sha1 = "9f02045d934dc030edad45944ea80dbd1f0ebea7"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.7"

[[deps.DataAPI]]
git-tree-sha1 = "cc70b17275652eb47bc9e5f81635981f13cea5c8"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.9.0"

[[deps.DataStructures]]
deps = ["Compat", "InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "3daef5523dd2e769dad2365274f760ff5f282c7d"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.18.11"

[[deps.DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[deps.DiffResults]]
deps = ["StaticArrays"]
git-tree-sha1 = "c18e98cba888c6c25d1c3b048e4b3380ca956805"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "1.0.3"

[[deps.DiffRules]]
deps = ["LogExpFunctions", "NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "9bc5dac3c8b6706b58ad5ce24cffd9861f07c94f"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.9.0"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[deps.DocStringExtensions]]
deps = ["LibGit2"]
git-tree-sha1 = "b19534d1895d702889b219c382a6e18010797f0b"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.6"

[[deps.Downloads]]
deps = ["ArgTools", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[[deps.EarCut_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "3f3a2501fa7236e9b911e0f7a588c657e822bb6d"
uuid = "5ae413db-bbd1-5e63-b57d-d24a61df00f5"
version = "2.2.3+0"

[[deps.EllipsisNotation]]
deps = ["ArrayInterface"]
git-tree-sha1 = "3fe985505b4b667e1ae303c9ca64d181f09d5c05"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
version = "1.1.3"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b3bfd02e98aedfa5cf885665493c5598c350cd2f"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.10+0"

[[deps.FFMPEG]]
deps = ["FFMPEG_jll"]
git-tree-sha1 = "b57e3acbe22f8484b4b5ff66a7499717fe1a9cc8"
uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
version = "0.4.1"

[[deps.FFMPEG_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "JLLWrappers", "LAME_jll", "Libdl", "Ogg_jll", "OpenSSL_jll", "Opus_jll", "Pkg", "Zlib_jll", "libass_jll", "libfdk_aac_jll", "libvorbis_jll", "x264_jll", "x265_jll"]
git-tree-sha1 = "d8a578692e3077ac998b50c0217dfd67f21d1e5f"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
version = "4.4.0+0"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "21efd19106a55620a188615da6d3d06cd7f6ee03"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.93+0"

[[deps.Formatting]]
deps = ["Printf"]
git-tree-sha1 = "8339d61043228fdd3eb658d86c926cb282ae72a8"
uuid = "59287772-0a20-5a39-b81b-1366585eb4c0"
version = "0.4.2"

[[deps.ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "LinearAlgebra", "LogExpFunctions", "NaNMath", "Preferences", "Printf", "Random", "SpecialFunctions", "StaticArrays"]
git-tree-sha1 = "2b72a5624e289ee18256111657663721d59c143e"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.24"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.4+0"

[[deps.FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.10+0"

[[deps.Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[deps.GLFW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libglvnd_jll", "Pkg", "Xorg_libXcursor_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll"]
git-tree-sha1 = "0c603255764a1fa0b61752d2bec14cfbd18f7fe8"
uuid = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
version = "3.3.5+1"

[[deps.GR]]
deps = ["Base64", "DelimitedFiles", "GR_jll", "HTTP", "JSON", "Libdl", "LinearAlgebra", "Pkg", "Printf", "Random", "Serialization", "Sockets", "Test", "UUIDs"]
git-tree-sha1 = "b9a93bcdf34618031891ee56aad94cfff0843753"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.63.0"

[[deps.GR_jll]]
deps = ["Artifacts", "Bzip2_jll", "Cairo_jll", "FFMPEG_jll", "Fontconfig_jll", "GLFW_jll", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pixman_jll", "Pkg", "Qt5Base_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "f97acd98255568c3c9b416c5a3cf246c1315771b"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
version = "0.63.0+0"

[[deps.GeometryBasics]]
deps = ["EarCut_jll", "IterTools", "LinearAlgebra", "StaticArrays", "StructArrays", "Tables"]
git-tree-sha1 = "58bcdf5ebc057b085e58d95c138725628dd7453c"
uuid = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
version = "0.4.1"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "a32d672ac2c967f3deb8a81d828afc739c838a06"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.68.3+2"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "344bf40dcab1073aca04aa0df4fb092f920e4011"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.14+0"

[[deps.Grisu]]
git-tree-sha1 = "53bb909d1151e57e2484c3d1b53e19552b887fb2"
uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe"
version = "1.0.2"

[[deps.HCubature]]
deps = ["Combinatorics", "DataStructures", "LinearAlgebra", "QuadGK", "StaticArrays"]
git-tree-sha1 = "134af3b940d1ca25b19bc9740948157cee7ff8fa"
uuid = "19dc6840-f33b-545b-b366-655c7e3ffd49"
version = "1.5.0"

[[deps.HTTP]]
deps = ["Base64", "Dates", "IniFile", "Logging", "MbedTLS", "NetworkOptions", "Sockets", "URIs"]
git-tree-sha1 = "0fa77022fe4b511826b39c894c90daf5fce3334a"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.9.17"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "8d511d5b81240fc8e6802386302675bdf47737b9"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.4"

[[deps.HypertextLiteral]]
git-tree-sha1 = "2b078b5a615c6c0396c77810d92ee8c6f470d238"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.3"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "f7be53659ab06ddc986428d3a9dcc95f6fa6705a"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.2"

[[deps.IfElse]]
git-tree-sha1 = "debdd00ffef04665ccbb3e150747a77560e8fad1"
uuid = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
version = "0.1.1"

[[deps.IniFile]]
deps = ["Test"]
git-tree-sha1 = "098e4d2c533924c921f9f9847274f2ad89e018b8"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.5.0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.IntervalSets]]
deps = ["Dates", "EllipsisNotation", "Statistics"]
git-tree-sha1 = "3cc368af3f110a767ac786560045dceddfc16758"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.5.3"

[[deps.InverseFunctions]]
deps = ["Test"]
git-tree-sha1 = "a7254c0acd8e62f1ac75ad24d5db43f5f19f3c65"
uuid = "3587e190-3f89-42d0-90ee-14403ec27112"
version = "0.1.2"

[[deps.IrrationalConstants]]
git-tree-sha1 = "7fd44fd4ff43fc60815f8e764c0f352b83c49151"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.1.1"

[[deps.IterTools]]
git-tree-sha1 = "fa6287a4469f5e048d763df38279ee729fbd44e5"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.4.0"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "642a199af8b68253517b80bd3bfd17eb4e84df6e"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.3.0"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "8076680b162ada2a031f707ac7b4953e30667a37"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.2"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "d735490ac75c5cb9f1b00d8b5509c11984dc6943"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.1.0+0"

[[deps.LAME_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "f6250b16881adf048549549fba48b1161acdac8c"
uuid = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
version = "3.100.1+0"

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e5b909bcf985c5e2605737d2ce278ed791b89be6"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.1+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"

[[deps.Latexify]]
deps = ["Formatting", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "Printf", "Requires"]
git-tree-sha1 = "a8f4f279b6fa3c3c4f1adadd78a621b13a506bce"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.15.9"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+1"

[[deps.Libgcrypt_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "64613c82a59c120435c067c2b809fc61cf5166ae"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.7+0"

[[deps.Libglvnd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "7739f837d6447403596a75d19ed01fd08d6f56bf"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+3"

[[deps.Libgpg_error_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c333716e46366857753e273ce6a69ee0945a6db9"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.42.0+0"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "42b62845d70a619f063a7da093d995ec8e15e778"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.1+1"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.35.0+0"

[[deps.Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "340e257aada13f95f98ee352d316c3bed37c8ab9"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.3.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.36.0+0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[deps.LogExpFunctions]]
deps = ["ChainRulesCore", "ChangesOfVariables", "DocStringExtensions", "InverseFunctions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "e5718a00af0ab9756305a0392832c8952c7426c1"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.6"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "3d3e902b31198a27340d0bf00d6ac452866021cf"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.9"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "Random", "Sockets"]
git-tree-sha1 = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.0.3"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[deps.Measures]]
git-tree-sha1 = "e498ddeee6f9fdb4551ce855a46f54dbd900245f"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.3.1"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "bf210ce90b6c9eed32d25dbcae1ebc565df2687f"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.0.2"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[deps.Mustache]]
deps = ["Printf", "Tables"]
git-tree-sha1 = "21d7a05c3b94bcf45af67beccab4f2a1f4a3c30a"
uuid = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
version = "1.0.12"

[[deps.NaNMath]]
git-tree-sha1 = "f755f36b19a5116bb580de457cda0c140153f283"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.6"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"

[[deps.Ogg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "887579a3eb005446d514ab7aeac5d1d027658b8f"
uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051"
version = "1.3.5+1"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"

[[deps.OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "15003dcb7d8db3c6c857fda14891a539a8f2705a"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.10+0"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "13652491f6856acfd2db29360e1bbcd4565d04f1"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.5+0"

[[deps.Opus_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "51a08fb14ec28da2ec7a927c4337e4332c2a4720"
uuid = "91d4177d-7536-5919-b921-800302f37372"
version = "1.3.2+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.4.1"

[[deps.PCRE_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b2a7af664e098055a7529ad1a900ded962bca488"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.44.0+0"

[[deps.Parsers]]
deps = ["Dates"]
git-tree-sha1 = "d7fa6237da8004be601e19bd6666083056649918"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.1.3"

[[deps.Pixman_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4f5d02549a10e20780a24fce72bea96b6329e29"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.40.1+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[deps.PlotThemes]]
deps = ["PlotUtils", "Requires", "Statistics"]
git-tree-sha1 = "a3a964ce9dc7898193536002a6dd892b1b5a6f1d"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "2.0.1"

[[deps.PlotUtils]]
deps = ["ColorSchemes", "Colors", "Dates", "Printf", "Random", "Reexport", "Statistics"]
git-tree-sha1 = "68604313ed59f0408313228ba09e79252e4b2da8"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "1.1.2"

[[deps.Plots]]
deps = ["Base64", "Contour", "Dates", "Downloads", "FFMPEG", "FixedPointNumbers", "GR", "GeometryBasics", "JSON", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "Requires", "Scratch", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs", "UnicodeFun", "Unzip"]
git-tree-sha1 = "71d65e9242935132e71c4fbf084451579491166a"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.25.4"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "Markdown", "Random", "Reexport", "UUIDs"]
git-tree-sha1 = "7711172ace7c40dc8449b7aed9d2d6f1cf56a5bd"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.29"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "2cf929d64681236a2e074ffafb8d568733d2e6af"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.2.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.PyCall]]
deps = ["Conda", "Dates", "Libdl", "LinearAlgebra", "MacroTools", "Serialization", "VersionParsing"]
git-tree-sha1 = "71fd4022ecd0c6d20180e23ff1b3e05a143959c2"
uuid = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
version = "1.93.0"

[[deps.PyPlot]]
deps = ["Colors", "LaTeXStrings", "PyCall", "Sockets", "Test", "VersionParsing"]
git-tree-sha1 = "14c1b795b9d764e1784713941e787e1384268103"
uuid = "d330b81b-6aea-500a-939a-2ce795aea3ee"
version = "2.10.0"

[[deps.Qt5Base_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Fontconfig_jll", "Glib_jll", "JLLWrappers", "Libdl", "Libglvnd_jll", "OpenSSL_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libxcb_jll", "Xorg_xcb_util_image_jll", "Xorg_xcb_util_keysyms_jll", "Xorg_xcb_util_renderutil_jll", "Xorg_xcb_util_wm_jll", "Zlib_jll", "xkbcommon_jll"]
git-tree-sha1 = "ad368663a5e20dbb8d6dc2fddeefe4dae0781ae8"
uuid = "ea2cea3b-5b76-57ae-a6ef-0a8af62496e1"
version = "5.15.3+0"

[[deps.QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "78aadffb3efd2155af139781b8a8df1ef279ea39"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.4.2"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.RecipesBase]]
git-tree-sha1 = "6bf3f380ff52ce0832ddd3a2a7b9538ed1bcca7d"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.2.1"

[[deps.RecipesPipeline]]
deps = ["Dates", "NaNMath", "PlotUtils", "RecipesBase"]
git-tree-sha1 = "7ad0dfa8d03b7bcf8c597f59f5292801730c55b8"
uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c"
version = "0.4.1"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "8f82019e525f4d5c669692772a6f4b0a58b06a6a"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.2.0"

[[deps.Roots]]
deps = ["CommonSolve", "Printf", "Setfield"]
git-tree-sha1 = "0abe7fc220977da88ad86d339335a4517944fea2"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
version = "1.3.14"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "0b4b7f1393cff97c33891da2a0bf69c6ed241fda"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.1.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Setfield]]
deps = ["ConstructionBase", "Future", "MacroTools", "Requires"]
git-tree-sha1 = "0afd9e6c623e379f593da01f20590bacc26d1d14"
uuid = "efcf1570-3423-57d1-acb7-fd33fddbac46"
version = "0.8.1"

[[deps.SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[deps.Showoff]]
deps = ["Dates", "Grisu"]
git-tree-sha1 = "91eddf657aca81df9ae6ceb20b959ae5653ad1de"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "1.0.3"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "b3363d7460f7d098ca0912c69b082f75625d7508"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.0.1"

[[deps.SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.SpecialFunctions]]
deps = ["ChainRulesCore", "IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "f0bccf98e16759818ffc5d97ac3ebf87eb950150"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "1.8.1"

[[deps.Static]]
deps = ["IfElse"]
git-tree-sha1 = "7f5a513baec6f122401abfc8e9c074fdac54f6c1"
uuid = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
version = "0.4.1"

[[deps.StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "88a559da57529581472320892576a486fa2377b9"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.3.1"

[[deps.Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[deps.StatsAPI]]
git-tree-sha1 = "d88665adc9bcf45903013af0982e2fd05ae3d0a6"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.2.0"

[[deps.StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "51383f2d367eb3b444c961d485c565e4c0cf4ba0"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.14"

[[deps.StructArrays]]
deps = ["Adapt", "DataAPI", "StaticArrays", "Tables"]
git-tree-sha1 = "2ce41e0d042c60ecd131e9fb7154a3bfadbf50d3"
uuid = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
version = "0.6.3"

[[deps.SymPy]]
deps = ["CommonEq", "CommonSolve", "Latexify", "LinearAlgebra", "Markdown", "PyCall", "RecipesBase", "SpecialFunctions"]
git-tree-sha1 = "8f8d948ed59ae681551d184b93a256d0d5dd4eae"
uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
version = "1.1.2"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[deps.TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "c06b2f539df1c6efa794486abfb6ed2022561a39"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

[[deps.Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "LinearAlgebra", "TableTraits", "Test"]
git-tree-sha1 = "bb1064c9a84c52e277f1096cf41434b675cd368b"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.6.1"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.URIs]]
git-tree-sha1 = "97bbe755a53fe859669cd907f2d96aee8d2c1355"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.3.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.UnicodeFun]]
deps = ["REPL"]
git-tree-sha1 = "53915e50200959667e78a92a418594b428dffddf"
uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1"
version = "0.4.1"

[[deps.Unitful]]
deps = ["ConstructionBase", "Dates", "LinearAlgebra", "Random"]
git-tree-sha1 = "b95e0b8a8d1b6a6c3e0b3ca393a7a285af47c264"
uuid = "1986cc42-f94f-5a68-af5c-568840ba703d"
version = "1.10.1"

[[deps.UnitfulUS]]
deps = ["Unitful"]
git-tree-sha1 = "aa8a8a140729fbca8c8d960ab488e0bf6b87feed"
uuid = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"
version = "0.2.0"

[[deps.Unzip]]
git-tree-sha1 = "34db80951901073501137bdbc3d5a8e7bbd06670"
uuid = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
version = "0.1.2"

[[deps.VersionParsing]]
git-tree-sha1 = "e575cf85535c7c3292b4d89d89cc29e8c3098e47"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.2.1"

[[deps.Wayland_jll]]
deps = ["Artifacts", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "3e61f0b86f90dacb0bc0e73a0c5a83f6a8636e23"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.19.0+0"

[[deps.Wayland_protocols_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "66d72dc6fcc86352f01676e8f0f698562e60510f"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.23.0+0"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "1acf5bdf07aa0907e0a37d3718bb88d4b687b74a"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.12+0"

[[deps.XSLT_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgcrypt_jll", "Libgpg_error_jll", "Libiconv_jll", "Pkg", "XML2_jll", "Zlib_jll"]
git-tree-sha1 = "91844873c4085240b95e795f692c4cec4d805f8a"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.34+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "5be649d550f3f4b95308bf0183b82e2582876527"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+4"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4e490d5c960c314f33885790ed410ff3a94ce67e"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+4"

[[deps.Xorg_libXcursor_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "12e0eb3bc634fa2080c1c37fccf56f7c22989afd"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+4"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fe47bd2247248125c428978740e18a681372dd4"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+4"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "b7c0aa8c376b31e4852b360222848637f481f8c3"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+4"

[[deps.Xorg_libXfixes_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "0e0dc7431e7a0587559f9294aeec269471c991a4"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+4"

[[deps.Xorg_libXi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "89b52bc2160aadc84d707093930ef0bffa641246"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+4"

[[deps.Xorg_libXinerama_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "26be8b1c342929259317d8b9f7b53bf2bb73b123"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+4"

[[deps.Xorg_libXrandr_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "34cea83cb726fb58f325887bf0612c6b3fb17631"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+4"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+4"

[[deps.Xorg_libpthread_stubs_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+3"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "daf17f441228e7a3833846cd048892861cff16d6"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[[deps.Xorg_libxkbfile_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "926af861744212db0eb001d9e40b5d16292080b2"
uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a"
version = "1.1.0+4"

[[deps.Xorg_xcb_util_image_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "0fab0a40349ba1cba2c1da699243396ff8e94b97"
uuid = "12413925-8142-5f55-bb0e-6d7ca50bb09b"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll"]
git-tree-sha1 = "e7fd7b2881fa2eaa72717420894d3938177862d1"
uuid = "2def613f-5ad1-5310-b15b-b15d46f528f5"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_keysyms_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "d1151e2c45a544f32441a567d1690e701ec89b00"
uuid = "975044d2-76e6-5fbe-bf08-97ce7c6574c7"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_renderutil_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "dfd7a8f38d4613b6a575253b3174dd991ca6183e"
uuid = "0d47668e-0667-5a69-a72c-f761630bfb7e"
version = "0.3.9+1"

[[deps.Xorg_xcb_util_wm_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "e78d10aab01a4a154142c5006ed44fd9e8e31b67"
uuid = "c22f9ab0-d5fe-5066-847c-f4bb1cd4e361"
version = "0.4.1+1"

[[deps.Xorg_xkbcomp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxkbfile_jll"]
git-tree-sha1 = "4bcbf660f6c2e714f87e960a171b119d06ee163b"
uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4"
version = "1.4.2+4"

[[deps.Xorg_xkeyboard_config_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xkbcomp_jll"]
git-tree-sha1 = "5c8424f8a67c3f2209646d4425f3d415fee5931d"
uuid = "33bec58e-1273-512f-9401-5d533626f822"
version = "2.27.0+4"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79c31e7844f6ecf779705fbc12146eb190b7d845"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+3"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[deps.Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "cc4bf3fdde8b7e3e9fa0351bdeedba1cf3b7f6e6"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.5.0+0"

[[deps.libass_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "HarfBuzz_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "5982a94fcba20f02f42ace44b9894ee2b140fe47"
uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
version = "0.15.1+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl", "OpenBLAS_jll"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"

[[deps.libfdk_aac_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "daacc84a041563f965be61859a36e17c4e4fcd55"
uuid = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
version = "2.0.2+0"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.38+0"

[[deps.libvorbis_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "c45f4e40e7aafe9d086379e5578947ec8b95a8fb"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.7+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[[deps.x264_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fea590b89e6ec504593146bf8b988b2c00922b2"
uuid = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
version = "2021.5.5+0"

[[deps.x265_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "ee567a171cce03570d77ad3a43e90218e38937a9"
uuid = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
version = "3.5.0+0"

[[deps.xkbcommon_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Wayland_jll", "Wayland_protocols_jll", "Xorg_libxcb_jll", "Xorg_xkeyboard_config_jll"]
git-tree-sha1 = "ece2350174195bb31de1a63bea3a41ae1aa593b6"
uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
version = "0.9.1+5"
"""

# ╔═╡ Cell order:
# ╟─5a8a475a-70d4-11ec-3d62-05e4dfa9447d
# ╟─5a80a77c-70d4-11ec-3e6e-8da4db53461e
# ╟─5a80a7ae-70d4-11ec-0d69-434c90bafd02
# ╠═5a80aeb6-70d4-11ec-360e-3d2969d4a911
# ╟─5a80b212-70d4-11ec-22a3-8d7aec70513b
# ╟─5a80b244-70d4-11ec-182a-b3f691490dc4
# ╟─5a80cd74-70d4-11ec-2514-83f61d04e183
# ╟─5a80cda6-70d4-11ec-2fe5-6d4a22ff554a
# ╟─5a80cdb8-70d4-11ec-1b01-35a16b8bba6d
# ╟─5a80cf40-70d4-11ec-01d7-0762bb0598a4
# ╟─5a80cf54-70d4-11ec-35ab-fb5849b77b1b
# ╟─5a80cf7c-70d4-11ec-1eb0-3f4aa986bb27
# ╟─5a80cf92-70d4-11ec-05a8-fd5eb62c0d48
# ╟─5a80cfa4-70d4-11ec-073e-797bd43c824e
# ╟─5a80cfae-70d4-11ec-3927-4fbfeca3b170
# ╟─5a80d09e-70d4-11ec-207c-c77a70a60981
# ╟─5a80d0d0-70d4-11ec-3566-996e5804d025
# ╟─5a80d102-70d4-11ec-1b38-01b8ee1ad5cb
# ╟─5a80d170-70d4-11ec-101a-df659677ccd4
# ╟─5a80d18c-70d4-11ec-3cc3-db036ce3870d
# ╟─5a80d6de-70d4-11ec-1242-351013343b87
# ╟─5a80d710-70d4-11ec-1e6a-036c31171614
# ╟─5a80d72c-70d4-11ec-1d3b-ed5b1cdba6d0
# ╟─5a80e034-70d4-11ec-2aca-6fe24d823ab1
# ╟─5a80e07a-70d4-11ec-1d77-e53f0779686c
# ╟─5a80e08e-70d4-11ec-3808-39aac7b8788c
# ╟─5a80e0a0-70d4-11ec-0024-711a75d53d72
# ╟─5a80e0ac-70d4-11ec-1b1f-91d0cc084457
# ╟─5a80e0c0-70d4-11ec-0c99-b37cc7a185e0
# ╟─5a80e0ca-70d4-11ec-1dba-fffa8d43ded8
# ╠═5a80e822-70d4-11ec-1c48-1be591f4a609
# ╟─5a80e868-70d4-11ec-21de-652ed5da027e
# ╟─5a80e872-70d4-11ec-33e4-e151638ffc59
# ╠═5a810208-70d4-11ec-13c1-357f853c6f2e
# ╟─5a810262-70d4-11ec-38b7-f56dce178218
# ╟─5a810294-70d4-11ec-3d6a-8dac416d8db3
# ╠═5a810726-70d4-11ec-2c9e-c147f6f989c1
# ╟─5a810758-70d4-11ec-1fe8-0d553f9c8a58
# ╟─5a810bfe-70d4-11ec-234c-1544614cfc26
# ╟─5a810c30-70d4-11ec-05fa-3b6da15c7d77
# ╟─5a810c4e-70d4-11ec-3af1-5bd0713bcbf0
# ╟─5a810c6c-70d4-11ec-3e29-691f0683f783
# ╟─5a810c80-70d4-11ec-2d13-03e7d847ebc6
# ╠═5a8112fc-70d4-11ec-0f99-dfc491446a32
# ╟─5a811310-70d4-11ec-3f91-2549c9d0adee
# ╠═5a8116f0-70d4-11ec-187a-f5f7f42597f1
# ╟─5a811702-70d4-11ec-12ae-8dc42b8ef3b0
# ╠═5a811aa4-70d4-11ec-22e3-af5d2576416f
# ╟─5a811ac2-70d4-11ec-30b5-215cbe9c170c
# ╠═5a811d2e-70d4-11ec-168b-69314f93f6e7
# ╟─5a813e58-70d4-11ec-32cb-113386096bd6
# ╟─5a813ea8-70d4-11ec-373f-8362e1b2a7cb
# ╟─5a813f02-70d4-11ec-36e3-efe81fba63a8
# ╠═5a814434-70d4-11ec-3e80-89cdd5a87d4a
# ╟─5a814466-70d4-11ec-06aa-cd2a20daaf12
# ╟─5a814484-70d4-11ec-2e5c-e54a743c7254
# ╟─5a814498-70d4-11ec-374c-f1aa8ea41eab
# ╟─5a87e410-70d4-11ec-1deb-85d353b8bcbf
# ╠═5a87f0e0-70d4-11ec-2694-85f9ce344a79
# ╟─5a87f16c-70d4-11ec-2138-417c4b065543
# ╟─5a88bc64-70d4-11ec-26bd-9bed32b448eb
# ╟─5a88bcfa-70d4-11ec-3a85-150c79432b3a
# ╟─5a88bd68-70d4-11ec-2d2f-15b092c15aee
# ╟─5a88bda6-70d4-11ec-1b28-bfdab99a82af
# ╟─5a88bdc2-70d4-11ec-3a9d-e9c46404467a
# ╟─5a88be4e-70d4-11ec-2785-27d09cab3e32
# ╠═5a88dab4-70d4-11ec-0562-7d7aa3ce82ef
# ╟─5a88db2a-70d4-11ec-37e2-6b2972a4bfc9
# ╠═5a88e220-70d4-11ec-3332-97896066acb4
# ╟─5a88e252-70d4-11ec-0079-f9889348c4af
# ╟─5a88e28e-70d4-11ec-0f22-430b69a6c8d2
# ╠═5a8900cc-70d4-11ec-17a6-01010d946dc8
# ╟─5a890124-70d4-11ec-0a59-670a52a1bd13
# ╟─5a890142-70d4-11ec-23d3-355e7832185e
# ╠═5a890318-70d4-11ec-0099-61fa93307220
# ╟─5a890386-70d4-11ec-111c-2f4b5d82d390
# ╟─5a8903c2-70d4-11ec-14da-478119301b98
# ╟─5a8903ea-70d4-11ec-1c85-f13a8ded61ee
# ╟─5a890412-70d4-11ec-35c4-2b72a5116e0d
# ╟─5a891d76-70d4-11ec-332f-b302756d45f1
# ╟─5a891dbe-70d4-11ec-3c0c-5be5068df621
# ╟─5a891dec-70d4-11ec-119d-f99e65bef145
# ╟─5a891e16-70d4-11ec-3666-bf98bf7be010
# ╟─5a891e50-70d4-11ec-180f-5548bbcf7631
# ╟─5a891e70-70d4-11ec-102f-fbbd1b948134
# ╟─5a891eb6-70d4-11ec-2431-8baa61f3ba2b
# ╟─5a891eca-70d4-11ec-36db-b1813968eb3d
# ╠═5a89332e-70d4-11ec-01db-7ff2fb8dc93a
# ╟─5a89337e-70d4-11ec-1ec5-b5029998610b
# ╟─5a893400-70d4-11ec-2b45-67d9d99830bb
# ╟─5a893432-70d4-11ec-1d50-6736693a7662
# ╠═5a893d56-70d4-11ec-23bc-1f7375cb1852
# ╟─5a893d92-70d4-11ec-15e2-937fe48648a1
# ╟─5a893dce-70d4-11ec-1f93-cb5cc79dd777
# ╟─5a893e0a-70d4-11ec-1e79-8175db1450a3
# ╟─5a893e32-70d4-11ec-0b15-77dab3633b55
# ╟─5a893f48-70d4-11ec-105e-09f34e208e23
# ╟─5a893f72-70d4-11ec-2d8e-233208278594
# ╟─5a894c56-70d4-11ec-2f17-c3dc3f4f3fef
# ╟─5a894cb0-70d4-11ec-17fe-651da3e91c68
# ╟─5a894ce2-70d4-11ec-21ae-b17f6f4a65ff
# ╟─5a894d1e-70d4-11ec-0fd1-635114017f4d
# ╟─5a894d3c-70d4-11ec-0a57-f59b334de963
# ╟─5a894d50-70d4-11ec-2d89-17068cd19093
# ╟─5a894d6e-70d4-11ec-23b2-65c03c02bbac
# ╟─5a894d82-70d4-11ec-32a8-477aa4bd4dae
# ╟─5a894db4-70d4-11ec-2fe3-35e110bf4f2c
# ╟─5a894df0-70d4-11ec-3ee3-7be18aadd86d
# ╟─5a894e2a-70d4-11ec-3a8b-817b8ae8a7b1
# ╟─5a8965e2-70d4-11ec-3604-336607e92c5c
# ╟─5a896652-70d4-11ec-3569-a147a8e6bfec
# ╟─5a89668c-70d4-11ec-210e-819687c5310d
# ╟─5a8966aa-70d4-11ec-051d-433499bc06da
# ╟─5a89674a-70d4-11ec-3344-cf58ab82248a
# ╟─5a89677c-70d4-11ec-116e-910a1a90635e
# ╟─5a8967ae-70d4-11ec-0148-b937ad738a17
# ╟─5a8967f4-70d4-11ec-3ae8-5b96d985383e
# ╟─5a896844-70d4-11ec-1959-b53148e2e052
# ╟─5a89688a-70d4-11ec-15b1-39e76b40c410
# ╟─5a8968b2-70d4-11ec-002c-87fbe9d11f79
# ╟─5a896916-70d4-11ec-3e7a-c1626f29c713
# ╟─5a896934-70d4-11ec-3ab3-8dd48f7b8a01
# ╟─5a89698e-70d4-11ec-24ca-cf5c71a1e938
# ╟─5a8969ac-70d4-11ec-10fa-f91f280edb62
# ╟─5a896f42-70d4-11ec-3c75-d58bcac7fd86
# ╟─5a896f7e-70d4-11ec-3d9b-e953c44c82e9
# ╟─5a896fb0-70d4-11ec-267e-6ddecc497196
# ╟─5a8970e6-70d4-11ec-1352-dda5609ce426
# ╟─5a899602-70d4-11ec-0b28-8b53904570ac
# ╟─5a899670-70d4-11ec-282e-d71d3e9e3a0d
# ╟─5a89971a-70d4-11ec-03bb-035f2c7c4402
# ╟─5a899742-70d4-11ec-3e05-f36514390651
# ╟─5a899f3a-70d4-11ec-03a3-53843366b36d
# ╟─5a899fda-70d4-11ec-2b8b-a9ff1b50a50d
# ╟─5a89a004-70d4-11ec-167f-091ecc9d8a41
# ╟─5a89a052-70d4-11ec-04bb-f72484021900
# ╟─5a89a070-70d4-11ec-27f0-9918f4048bfe
# ╟─5a89a096-70d4-11ec-23a7-a55cdad4930a
# ╟─5a89a0c0-70d4-11ec-27be-7f8f5ffaaeb5
# ╠═5a89a8a2-70d4-11ec-2a41-31e351fc27b5
# ╟─5a89a9b2-70d4-11ec-28d2-7162aeeb8067
# ╟─5a89b29a-70d4-11ec-2c27-f156923d8b43
# ╟─5a89b416-70d4-11ec-04e4-d3f778f263b8
# ╟─5a89bdda-70d4-11ec-0f54-b3c9662bc1c9
# ╟─5a89be8c-70d4-11ec-3f31-5bd74e22000e
# ╟─5a89c6c2-70d4-11ec-2468-8d58cba3945b
# ╟─5a89c794-70d4-11ec-36d0-7dab59c6b02a
# ╟─5a89d0a2-70d4-11ec-2998-a1a5cf13c624
# ╟─5a89d0e0-70d4-11ec-0f39-1325e28a6a9a
# ╟─5a89d16c-70d4-11ec-2d9f-abf165d818d1
# ╟─5a89db1e-70d4-11ec-1f1f-1166c42a572e
# ╟─5a89dbb0-70d4-11ec-03ed-cd222e32832e
# ╟─5a89e242-70d4-11ec-2c1c-bf5089221c6d
# ╟─5a89e2e2-70d4-11ec-1725-33e13859ea0b
# ╟─5a89e80a-70d4-11ec-3a4c-410f47245611
# ╟─5a89e88c-70d4-11ec-256c-3f495811cc7e
# ╟─5a89ef30-70d4-11ec-186a-d1f7af7e4230
# ╟─5a89ef6e-70d4-11ec-346b-fd73c6713d20
# ╟─5a89efb2-70d4-11ec-3790-7b4c81a0b222
# ╟─5a89efbc-70d4-11ec-3a4b-47f66634b235
# ╟─5a89efce-70d4-11ec-3e18-33002c7c5195
# ╟─5a89f296-70d4-11ec-282c-5f9d90667707
# ╟─5a89f2aa-70d4-11ec-13de-8790066331dc
# ╟─5a8a130c-70d4-11ec-3340-59741685d6c8
# ╟─5a8a1336-70d4-11ec-0b2d-754fe3cde64a
# ╟─5a8a1370-70d4-11ec-3f94-b79a6fdc88e0
# ╟─5a8a1b22-70d4-11ec-0b03-1b27fbb530c3
# ╟─5a8a1b42-70d4-11ec-040d-b3641511ed11
# ╟─5a8a1b68-70d4-11ec-1fe7-11eff37b220c
# ╟─5a8a22b6-70d4-11ec-02b9-99adaaa7954d
# ╟─5a8a22d4-70d4-11ec-2057-e77b2792034d
# ╟─5a8a22fc-70d4-11ec-1e8f-cf4c11fbe99f
# ╟─5a8a26a8-70d4-11ec-10b2-61da8893aa89
# ╟─5a8a26bc-70d4-11ec-13c0-8d58799ac82f
# ╟─5a8a26da-70d4-11ec-218c-197c7a9bc864
# ╠═5a8a29fa-70d4-11ec-0d43-f7909d7b2ea6
# ╟─5a8a2e96-70d4-11ec-3d39-c181d62c9b77
# ╟─5a8a2eb4-70d4-11ec-23f0-a99bc01424bc
# ╟─5a8a2edc-70d4-11ec-3d05-5b6fa29b97bf
# ╟─5a8a2eee-70d4-11ec-2a6d-1b9bbac446ea
# ╟─5a8a3404-70d4-11ec-3e77-97130b87d085
# ╟─5a8a3422-70d4-11ec-05a0-b7c12c32ecf7
# ╟─5a8a344a-70d4-11ec-2de9-89c4dce3b1ef
# ╟─5a8a39ae-70d4-11ec-11c2-69a382ecd97e
# ╟─5a8a39ca-70d4-11ec-1ff7-9fd242575e24
# ╟─5a8a39ea-70d4-11ec-25dc-a7cf62c8eaed
# ╟─5a8a3a12-70d4-11ec-07a4-3396ba09fb93
# ╠═5a8a3e22-70d4-11ec-13de-cb5ddf461ceb
# ╟─5a8a3e4a-70d4-11ec-0b9f-c58092d10d3a
# ╟─5a8a3e54-70d4-11ec-1aab-7fd3f8e10ddc
# ╟─5a8a42aa-70d4-11ec-11fe-ad1c7df684cf
# ╟─5a8a42be-70d4-11ec-0427-0122c70ebb29
# ╟─5a8a42de-70d4-11ec-1f3c-119e7e7d000a
# ╟─5a8a4750-70d4-11ec-20e7-45c106f45cff
# ╟─5a8a477a-70d4-11ec-255a-e14677a1f335
# ╟─5a8a4782-70d4-11ec-2c3c-49b84058e2af
# ╟─5a8a478c-70d4-11ec-1d89-076996d20f5c
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
