### A Pluto.jl notebook ###
# v0.17.2

using Markdown
using InteractiveUtils

# ╔═╡ 16af3316-53c0-11ec-3a0f-618d61ab9384
using CalculusWithJulia    # loads the `SpecialFunctions` package

# ╔═╡ 16af65e6-53c0-11ec-31ab-dfb9afb3123d
begin
	using CalculusWithJulia.WeaveSupport
	using Plots
	__DIR__, __FILE__ = :precalc, :logical_expressions
	nothing
end

# ╔═╡ 16b7d9d8-53c0-11ec-1155-7f4d8dc916a4
using PlutoUI

# ╔═╡ 16b7d9ba-53c0-11ec-2db3-3bcd6a3009eb
HTML("""
<div class="admonition info">
<a href="https://CalculusWithJulia.github.io">
<img src="https://raw.githubusercontent.com/jverzani/CalculusWithJulia.jl/master/CwJ/misc/logo.png" alt="Calculus with Julia" width="48" />
</a>
<span style="font-size:32px">Calculus With Julia</span>
</div>
""")


# ╔═╡ 16aec514-53c0-11ec-2a33-871e1c8bf520
md"""# Inequalities, Logical expressions
"""

# ╔═╡ 16aec73a-53c0-11ec-161b-dbdf0de58e89
md"""In the following we use the following package:
"""

# ╔═╡ 16af68b6-53c0-11ec-33ca-97033b256f68
md"""## Boolean values
"""

# ╔═╡ 16af6d84-53c0-11ec-0aee-817231a7b384
md"""In mathematics it is common to test if an expression is true or false. For example, is the point $(1,2)$ inside the disc $x^2 + y^2 \leq 1$? We would check this by substituting $1$ for $x$ and $2$ for $y$, evaluating both sides of the inequality and then assessing if the relationship is true or false. In this case, we end up with a comparison of $5 \leq 1$, which we of course know is false.
"""

# ╔═╡ 16af6fb4-53c0-11ec-1ac9-6faf64e7cce1
md"""`Julia` provides numeric comparisons that allow this notation to be exactly mirrored:
"""

# ╔═╡ 16b14bf4-53c0-11ec-1fc7-2147aa8d6010
let
	x, y = 1, 2
	x^2 + y^2 <= 1
end

# ╔═╡ 16b1514e-53c0-11ec-060e-079db87a9554
md"""The response is `false`, as expected. `Julia` provides [Boolean](http://en.wikipedia.org/wiki/Boolean_data_type) values `true` and `false` for such questions. The same process is followed as was described mathematically.
"""

# ╔═╡ 16b1524a-53c0-11ec-0921-e119ec5298b7
md"""The set of numeric comparisons is nearly the same as the mathematical counterparts: `<`, `<=`, `==`, `>=`, `>`. The syntax for less than or equal can also be represented with the Unicode `≤` (generated by `\le[tab]`). Similarly, for greater than or equal, there is `\ge[tab]`.
"""

# ╔═╡ 16b1da30-53c0-11ec-0c56-9507494ff28b
alert("The use of `==` is necessary, as `=` is used for assignment.")

# ╔═╡ 16b1dbc6-53c0-11ec-058a-5d1ffb1eb25d
md"""The `!` operator takes a boolean value and negates it. It uses prefix notation:
"""

# ╔═╡ 16b1e8d4-53c0-11ec-1274-5f666d58ebf8
!true

# ╔═╡ 16b1ea48-53c0-11ec-093c-e993a8056c40
md"""For  convenience, `a != b` can be used in place of `!(a == b)`.
"""

# ╔═╡ 16b1eb36-53c0-11ec-1c6f-c9785769afe1
md"""## Algebra of inequalities
"""

# ╔═╡ 16b1ebfe-53c0-11ec-1e49-85bbe1375432
md"""To illustrate, let's see that the algebra of expressions works as expected.
"""

# ╔═╡ 16b1ed02-53c0-11ec-1e9c-db0fad8b3ccf
md"""For example, if $a < b$ then for any $c$ it is also true that $a + c < b + c$.
"""

# ╔═╡ 16b1eddc-53c0-11ec-0200-3747fa27aef7
md"""We can't "prove" this through examples, but we can investigate it by the choice of various values of $a$, $b$, and $c$. For example:
"""

# ╔═╡ 16b2c132-53c0-11ec-23df-2ded88db8924
let
	a,b,c = 1,2,3
	a < b, a + c < b + c
end

# ╔═╡ 16b2c29a-53c0-11ec-2306-c7797b538c6a
md"""Or in reverse:
"""

# ╔═╡ 16b33644-53c0-11ec-14d3-8963e015c5c9
let
	a,b,c = 3,2,1
	a < b, a + c < b + c
end

# ╔═╡ 16b336d0-53c0-11ec-37e9-51475119e239
md"""Trying other choices will show that the two answers are either both `false` or both `true`.
"""

# ╔═╡ 16b3d554-53c0-11ec-2edf-577ee8153bdd
alert(""" Well, almost... When `Inf` or `NaN` are involved, this may not hold, for example `1 + Inf < 2 + Inf` is actually `false`. As would be `1 + (typemax(1)-1) < 2 + (typemax(1)-1)`.""")

# ╔═╡ 16b3d694-53c0-11ec-03c9-817787e93f5a
md"""So adding or subtracting most any finite value from an inequality will preserve the inequality, just as it does for equations.
"""

# ╔═╡ 16b3d6d2-53c0-11ec-0ba6-dfcaf8cdba76
md"""What about addition and multiplication?
"""

# ╔═╡ 16b40600-53c0-11ec-04d4-c9737b321004
md"""Consider the case $a < b$ and $c > 0$. Then $ca < cb$. Here we investigate using 3 random values (which will be positive):
"""

# ╔═╡ 16b42430-53c0-11ec-010e-3be296410095
let
	a,b,c = rand(3)   # 3 random numbers in [0,1)
	a < b, c*a < c*b
end

# ╔═╡ 16b424be-53c0-11ec-3b61-dd69b2699f15
md"""Whenever these two commands are run, the two logical values should be identical, even though the specific values of `a`, `b`, and `c` will vary.
"""

# ╔═╡ 16b425e0-53c0-11ec-0f4d-db45b620abc9
md"""The restriction that $c > 0$ is needed. For example, if $c = -1$, then we have $a < b$ if and only if $-a > -b$. That is the inequality is "flipped."
"""

# ╔═╡ 16b43e20-53c0-11ec-1744-01daacfbabe4
let
	a,b = rand(2)
	a < b, -a > -b
end

# ╔═╡ 16b43f44-53c0-11ec-2b70-0fbc6926fa69
md"""Again, whenever this is run, the two logical values should be the same. The values $a$ and $-a$ are the same distance from $0$, but on opposite sides. Hence if $0 < a < b$, then $b$ is farther from $0$ than $a$, so $-b$ will be farther from $0$ than $-a$, which in this case says $-b < -a$, as expected.
"""

# ╔═╡ 16b43fba-53c0-11ec-15d1-adc988e201bf
md"""Finally, we have the case of division. The relation of $x$ and $1/x$ (for $x > 0$) is that the farther $x$ is from $0$, the closer $1/x$ is to $0$. So large values of $x$ make small values of $1/x$. This leads to this fact for $a,b > 0$: $a < b$ if and only if $1/a > 1/b$.
"""

# ╔═╡ 16b44052-53c0-11ec-0bf0-5d297a617aa8
md"""We can check with random values again:
"""

# ╔═╡ 16b44746-53c0-11ec-1fdf-092e7aeba1e6
let
	a,b = rand(2)
	a < b, 1/a > 1/b
end

# ╔═╡ 16b4476e-53c0-11ec-1ffb-5d2d87aedbaf
md"""In summary we investigated numerically that the following hold:
"""

# ╔═╡ 16b457fe-53c0-11ec-056f-1d0f1b25676a
md"""  * `a < b` if and only if `a + c < b + c` for all finite `a`, `b`, and `c`.
  * `a < b` if and only if `c*a < c*b` for all finite `a` and `b`, and finite, positive `c`.
  * `a < b` if and only if `-a > -b` for all finite `a` and `b`.
  * `a < b` if and only if `1/a > 1/b` for all finite, positive `a` and `b`.
"""

# ╔═╡ 16b45874-53c0-11ec-2c45-6349cc541cf8
md"""## Some examples
"""

# ╔═╡ 16b45a92-53c0-11ec-047f-b3a57613deaf
md"""We now show some inequalities highlighted on this  [Wikipedia](http://en.wikipedia.org/wiki/Inequality_%28mathematics%29) page.
"""

# ╔═╡ 16b4727a-53c0-11ec-2900-0d05a16c4aa4
md"""Numerically investigate the fact $e^x \geq 1 + x$ by showing it is true for three different values of $x$. We pick $x=-1$, $0$, and $1$:
"""

# ╔═╡ 16b4bbd6-53c0-11ec-1206-8fc32484b780
let
	x = -1; exp(x) >= 1 + x
	x =  0; exp(x) >= 1 + x
	x =  1; exp(x) >= 1 + x
end

# ╔═╡ 16b4bd70-53c0-11ec-2e54-03c73d5f9761
md"""Now, let's investigate that for any distinct real numbers, $a$ and $b$, that
"""

# ╔═╡ 16b4c108-53c0-11ec-2962-a31a5fa47290
md"""```math
\frac{e^b - e^a}{b - a} > e^{(a+b)/2}
```
"""

# ╔═╡ 16b4c1a8-53c0-11ec-19b2-4599ee730808
md"""For this, we use `rand(2)` to generate two random numbers in $[0,1)$:
"""

# ╔═╡ 16b4cab8-53c0-11ec-1b47-0d97e23c8867
let
	a, b = rand(2)
	(exp(b) - exp(a)) / (b-a) > exp((a+b)/2)
end

# ╔═╡ 16b4cbb2-53c0-11ec-385f-4b813f3dac2f
md"""This should evaluate to `true` for any random choice of `a` and `b` returned by `rand(2)`.
"""

# ╔═╡ 16b4cc52-53c0-11ec-3051-3d2d54d06445
md"""Finally, let's investigate the fact that the harmonic mean, $2/(1/a + 1/b)$ is less than or equal to the geometric mean, $\sqrt{ab}$, which is less than or equal to the quadratic mean, $\sqrt{a^2 + b^2}/\sqrt{2}$, using two randomly chosen values:
"""

# ╔═╡ 16b4eb24-53c0-11ec-27f2-576bb9dcbbbd
let
	a, b = rand(2)
	h = 2 / (1/a + 1/b)
	g = (a * b) ^ (1 / 2)
	q = sqrt((a^2 + b^2) / 2)
	h <= g, g <= q
end

# ╔═╡ 16b4ebec-53c0-11ec-2128-5ba4a40cd7ed
md"""## Chaining, combining expressions: absolute values
"""

# ╔═╡ 16b4ec5a-53c0-11ec-2755-511aac0eddc1
md"""The absolute value notation can be defined through cases:
"""

# ╔═╡ 16b4ec8c-53c0-11ec-2911-3df115a82e09
md"""```math
\lvert x\rvert = \begin{cases}
x & x \geq 0\\
-x & \text{otherwise}.
\end{cases}
```
"""

# ╔═╡ 16b4ece6-53c0-11ec-186e-4b7681eebc8a
md"""The interpretation of $\lvert x\rvert$, as the distance on the number line of $x$ from $0$, means that many relationships are naturally expressed in terms of absolute values. For example, a simple shift: $\lvert x -c\rvert$ is related to the distance $x$ is from the number $c$. As common as they are, the concept can still be confusing when inequalities are involved.
"""

# ╔═╡ 16b515ae-53c0-11ec-2dd8-ff6885c9709b
md"""For example, the expression $\lvert x - 5\rvert < 7$ has solutions which are all values of $x$ within $7$ units of $5$. This would be the values $-2< x < 12$. If this isn't immediately intuited, then formally $\lvert x - 5\rvert <7$ is a compact representation of a chain of inequalities: $-7 < x-5 < 7$. (Which is really two combined inequalities: $-7 < x-5$ *and* $x-5 < 7$.) We can "add" 5 to each side to get $-2 < x < 12$, using the fact that adding by a finite number does not change the inequality sign.
"""

# ╔═╡ 16b51612-53c0-11ec-1763-d5606514ed94
md"""Julia's precedence for logical expressions, allows such statements to mirror the mathematical notation:
"""

# ╔═╡ 16b51d24-53c0-11ec-1b12-5dd6da7d0200
begin
	x = 18
	abs(x - 5) < 7
end

# ╔═╡ 16b51dd8-53c0-11ec-0673-851c948f89de
md"""This is to be expected, but we could also have written:
"""

# ╔═╡ 16b524cc-53c0-11ec-247a-0b9bebf1d337
-7 < x - 5 < 7

# ╔═╡ 16b5261e-53c0-11ec-1c0c-e7ae3b21cd3d
md"""Read aloud this would be "minus 7 is less than x minus 5 **and** x minus 5 is less than 7".
"""

# ╔═╡ 16b527e2-53c0-11ec-2db1-915608f747c9
md"""The "and" equations can be combined as above with a natural notation. However, an equation like $\lvert x - 5\rvert > 7$ would emphasize an **or** and be "x minus 5 less than minus 7 **or** x minus 5 greater than 7". Expressing this requires some new notation.
"""

# ╔═╡ 16b529b8-53c0-11ec-03e8-19ef164fac03
md"""The *boolean shortcut operators* `&&` and `||` implement "and" and "or." (There are also *bitwise* boolean operators `&` and `|`, but we only describe the former.)
"""

# ╔═╡ 16b529e0-53c0-11ec-3807-89c06252e092
md"""Thus we could write $-7 < x-5 < 7$ as
"""

# ╔═╡ 16b57b3e-53c0-11ec-13af-99bad9a90732
(-7 < x - 5) && (x - 5 < 7)

# ╔═╡ 16b57cec-53c0-11ec-14e3-c91ea4f5e173
md"""and could write $\lvert x-5\rvert > 7$ as
"""

# ╔═╡ 16b58714-53c0-11ec-18cc-0755a70e5fd4
(x - 5 < -7) || (x - 5 > 7)

# ╔═╡ 16b58804-53c0-11ec-1fb4-1be5cb49ef4f
md"""(The first expression is false for $x=18$ and the second expression true, so the "or"ed result is `true` and the "and" result if `false`.)
"""

# ╔═╡ 16b58c50-53c0-11ec-2dd4-894944e205ff
md"""##### Example
"""

# ╔═╡ 16b58d72-53c0-11ec-2407-09540dabd319
md"""One of [DeMorgan's Laws](http://en.wikipedia.org/wiki/De_Morgan%27s_laws) states that "not (A and B)" is the same as "(not A) or (not B)". This is a kind of distributive law for "not", but note how the "and" changes to "or". We can verify this law systematically. For example, the following shows it true for 1 of the 4 possible cases for the pair `A`, `B` to take:
"""

# ╔═╡ 16b596a0-53c0-11ec-206b-11d0acd65780
begin
	A,B = true, false  ## also true, true; false, true; and false, false
	!(A && B) == !A || !B
end

# ╔═╡ 16b59740-53c0-11ec-0c28-974b7a6e527e
md"""## Precedence
"""

# ╔═╡ 16b5995c-53c0-11ec-3af2-4902a2e40ec8
md"""The question of when parentheses are needed and when they are not is answered by the [precedence](http://julia.readthedocs.org/en/latest/manual/mathematical-operations/#operator-precedence)  rules implemented. Earlier, we wrote
"""

# ╔═╡ 16b5a296-53c0-11ec-1b8c-b9f6906fdee1
(x - 5 < -7) || (x - 5 > 7)

# ╔═╡ 16b5a348-53c0-11ec-3293-9d110d958530
md"""To represent $\lvert x-5\rvert > 7$. Were the parentheses necessary? Let's just check.
"""

# ╔═╡ 16b5aaaa-53c0-11ec-2c04-6f41f3927e58
x - 5 < -7 || x - 5 > 7

# ╔═╡ 16b5ab4a-53c0-11ec-1eb5-9f2cdef53688
md"""So no, they were not.
"""

# ╔═╡ 16b5acd0-53c0-11ec-2d2a-37262767f9d5
md"""An operator (such as `<`, `>`, `||` above) has an associated associativity and precedence. The associativity is whether an expression like `a - b - c` is `(a-b) - c` or `a - (b-c)`. The former being left associative, the latter right. Of issue here is *precedence*, as in with two or more different operations, which happens first, second, $\dots$.
"""

# ╔═╡ 16b5ad5c-53c0-11ec-190e-cba71689a082
md"""The table in the manual on [operator precedence and associativity](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Operator-Precedence-and-Associativity) shows that for these operations "control flow" (the `&&` above) is lower than "comparisons" (the `<`, `>`), which are lower than "Addition" (the `-` above). So the expression without parentheses would be equivalent to:
"""

# ╔═╡ 16b5d32c-53c0-11ec-1510-db07f8cb1117
((x-5) < -7) && ((x-5) > 7)

# ╔═╡ 16b5d438-53c0-11ec-3125-1fc0873562d7
md"""(This is different than the precedence of the bitwise boolean operators, which have `&` with "Multiplication" and `|` with "Addition", so `x-5 < 7 | x - 5 > 7` would need parentheses.)
"""

# ╔═╡ 16b5d4dc-53c0-11ec-3278-d32c1e7b5aeb
md"""A thorough understanding of the precedence rules can help eliminate unnecessary parentheses, but in most cases it is easier just to put them in.
"""

# ╔═╡ 16b5d502-53c0-11ec-327a-add85c50c600
md"""## Arithmetic with
"""

# ╔═╡ 16b5d5c0-53c0-11ec-0237-ad8e54713641
md"""For convenience, basic arithmetic can be performed with Boolean values, `false` becomes $0$ and true $1$. For example, both these expressions make sense:
"""

# ╔═╡ 16b5e362-53c0-11ec-2a79-5f2bccafc494
true + true + false, false * 1000

# ╔═╡ 16b5e3da-53c0-11ec-1012-31c1b73090fb
md"""The first example shows a common means used to count the number of `true` values in a collection of Boolean values - just add them.
"""

# ╔═╡ 16b5e4ac-53c0-11ec-0383-f94b93235864
md"""This can be cleverly exploited. For example, the following expression returns `x` when it is positive and $0$ otherwise:
"""

# ╔═╡ 16b5e984-53c0-11ec-37d5-6fd0bcd54fdb
(x > 0) * x

# ╔═╡ 16b5ea6a-53c0-11ec-15cf-9d0dee5bc1d2
md"""There is a built in function, `max` that can be used for this: `max(0, x)`.
"""

# ╔═╡ 16b5eba0-53c0-11ec-2f90-69a13ca5af4b
md"""This expression returns `x` if it is between $-10$ and $10$ and otherwise $-10$ or $10$ depending on whether $x$ is negative or positive.
"""

# ╔═╡ 16b62c6e-53c0-11ec-1244-6b86388df3b0
(x < -10)*(-10) + (x >= -10)*(x < 10) * x + (x>=10)*10

# ╔═╡ 16b62d48-53c0-11ec-05a0-a9946fc1ff88
md"""The `clamp(x, a, b)` performs this task more generally, and is used as in `clamp(x, -10, 10)`.
"""

# ╔═╡ 16b62d68-53c0-11ec-0f04-39385e939e98
md"""## Questions
"""

# ╔═╡ 16b6458c-53c0-11ec-34e0-ddf6f8387240
md"""###### Question
"""

# ╔═╡ 16b64672-53c0-11ec-3c51-cba776096f14
md"""Is `e^pi` or `pi^e` greater?
"""

# ╔═╡ 16b65b6c-53c0-11ec-002b-15827bab88fc
let
	choices = [
	"`e^pi` is greater than `pi^e`",
	"`e^pi` is equal to `pi^e`",
	"`e^pi` is less than `pi^e`"
	]
	ans = 1
	radioq(choices, ans)
end

# ╔═╡ 16b65bb2-53c0-11ec-1979-39195b7571f0
md"""###### Question
"""

# ╔═╡ 16b65c66-53c0-11ec-0fae-930546634c96
md"""Is $\sin(1000)$ positive?
"""

# ╔═╡ 16b666b6-53c0-11ec-0334-1f50d36619a6
let
	ans = (sin(1000) > 0)
	yesnoq(ans)
end

# ╔═╡ 16b666f2-53c0-11ec-1dc5-4da83ee67bdc
md"""###### Question
"""

# ╔═╡ 16b66742-53c0-11ec-0617-b74a1fdfbf0d
md"""Suppose you know $0 < a < b$. What can you say about the relationship between $-1/a$ and $-1/b$?
"""

# ╔═╡ 16b6866e-53c0-11ec-3666-d99f4fa29326
let
	choices = [
	"``-1/a < -1/b``",
	"``-1/a > -1/b``",
	raw"``-1/a \geq -1/b``"]
	ans = 3
	radioq(choices, ans)
end

# ╔═╡ 16b686bc-53c0-11ec-0b70-95353cd190a2
md"""###### Question
"""

# ╔═╡ 16b6881c-53c0-11ec-21c2-7d10344a9792
md"""Suppose you know $a < 0 < b$, is it true that $1/a > 1/b$?
"""

# ╔═╡ 16b69b54-53c0-11ec-26da-8b7d999b986c
let
	choices = ["Yes, it is always true.",
	           "It can sometimes be true, though not always.",
		   L"It is never true, as $1/a$ is negative and $1/b$ is positive"]
	ans = 3
	radioq(choices, ans)
end

# ╔═╡ 16b69b86-53c0-11ec-1b73-efaa07298ed9
md"""###### Question
"""

# ╔═╡ 16b69d4a-53c0-11ec-09fd-874cfe9ddaed
md"""The `airyai` [function](http://en.wikipedia.org/wiki/Airy_function) is a special function named after a British Astronomer who realized the function's value in his studies of the rainbow. The `SpecialFunctions` package must be loaded to include this function, which is done with the accompanying package `CalculusWithJulia`.
"""

# ╔═╡ 16b6a108-53c0-11ec-0b9f-05d81d4b9cbe
airyai(0)

# ╔═╡ 16b6a1d0-53c0-11ec-0cd2-85555bdf8dbc
md"""It is known that this function is always positive for $x > 0$, though not so for negative values of $x$. Which of these indicates the first negative value : `airyai(-1) <0`, `airyai(-2) < 0`, ..., or `airyai(-5) < 0`?
"""

# ╔═╡ 16b6c7b6-53c0-11ec-1816-4d0bd713ff62
let
	choices = ["`airyai($i) < 0`" for i in -1:-1:-5]
	ans = 3
	radioq(choices, ans, keep_order=true)
end

# ╔═╡ 16b6c868-53c0-11ec-1634-45613bb43ecc
md"""###### Question
"""

# ╔═╡ 16b6c8ae-53c0-11ec-1ba7-315d5d27ca36
md"""By trying three different values of $x > 0$ which of these could possibly be always true:
"""

# ╔═╡ 16b702b0-53c0-11ec-01db-15319cf063c3
let
	choices = ["`x^x <= (1/e)^(1/e)`",
	           "`x^x == (1/e)^(1/e)`",
	           "`x^x >= (1/e)^(1/e)`"]
	ans = 3
	radioq(choices, ans)
end

# ╔═╡ 16b7030a-53c0-11ec-2e88-a9f03e889aa2
md"""###### Question
"""

# ╔═╡ 16b704a4-53c0-11ec-068f-e9a802d41913
md"""Student logic says $(x+y)^p = x^p + y^p$. Of course, this isn't correct for all $p$ and $x$. By trying a few points, which is true when $x,y > 0$ and $0 < p < 1$:
"""

# ╔═╡ 16b712fa-53c0-11ec-27b0-9fadea96c0de
let
	choices = ["`(x+y)^p < x^p + y^p`",
	           "`(x+y)^p == x^p + y^p`",
	           "`(x+y)^p > x^p + y^p`"]
	ans = 1
	radioq(choices, ans)
end

# ╔═╡ 16b713b8-53c0-11ec-05c5-55c136a8b81f
md"""###### Question
"""

# ╔═╡ 16b7144e-53c0-11ec-102c-6d7d6ce98af8
md"""According to Wikipedia, one of the following inequalities is always true for $a, b > 0$ (as proved by I. Ilani in JSTOR, AMM, Vol.97, No.1, 1990). Which one?
"""

# ╔═╡ 16b72074-53c0-11ec-1a62-990af43d7d97
let
	choices = ["`a^a + b^b <= a^b + b^a`",
	           "`a^a + b^b >= a^b + b^a`",
		   "`a^b + b^a <= 1`"]
	ans = 2
	radioq(choices, ans)
end

# ╔═╡ 16b7210a-53c0-11ec-3ac9-c1ebee56ba42
md"""###### Question
"""

# ╔═╡ 16b72150-53c0-11ec-33d0-7bf098b54362
md"""Is $3$ in the set $\lvert x - 2\rvert < 1/2$?
"""

# ╔═╡ 16b74144-53c0-11ec-09a7-a3d5e65a9fe8
let
	val = abs(3-2) < 1/2
	yesnoq(val)
end

# ╔═╡ 16b74180-53c0-11ec-0063-5fc4fef76353
md"""###### Question
"""

# ╔═╡ 16b74202-53c0-11ec-0b87-695b6d983c83
md"""Which of the following is equivalent to $\lvert x - a\rvert > b$:
"""

# ╔═╡ 16b74f7c-53c0-11ec-338f-eb4e1d892634
let
	choices = [raw"``-b < x - a < b``",
	           raw"`` -b < x-a \text{ and } x - a < b``",
	           raw"``x - a < -b \text{ or } x - a > b``"]
	ans = 3
	radioq(choices, ans)
end

# ╔═╡ 16b75044-53c0-11ec-3045-1d2c5ced623e
md"""###### Question
"""

# ╔═╡ 16b750ee-53c0-11ec-39d0-ed51879c0ebf
md"""If $\lvert x - \pi\rvert < 1/10$ is $\lvert \sin(x) - \sin(\pi)\rvert < 1/10$?
"""

# ╔═╡ 16b751c8-53c0-11ec-3705-97b4ef6036c1
md"""Guess an answer based on a few runs of
"""

# ╔═╡ 16b75210-53c0-11ec-1b29-9b6b7659fca4
md"""```
x = pi + 1/10 * (2rand()-1)
abs(x - pi) < 1/10, abs(sin(x) - sin(pi)) < 1/10
```"""

# ╔═╡ 16b757da-53c0-11ec-195a-a7a6feddec66
let
	booleanq(true)
end

# ╔═╡ 16b75814-53c0-11ec-237b-556342a6ff93
md"""###### Question
"""

# ╔═╡ 16b758c8-53c0-11ec-1b13-292422eaa548
md"""Does `12` satisfy $\lvert x - 3\rvert + \lvert x-9\rvert > 12$?
"""

# ╔═╡ 16b75e90-53c0-11ec-2058-b95477b0893c
let
	x = 12
	val = (abs(x -3) + abs(x-9) > 12)
	yesnoq(val)
end

# ╔═╡ 16b75ecc-53c0-11ec-26a6-1b25783e16d0
md"""###### Question
"""

# ╔═╡ 16b7600c-53c0-11ec-08f6-8db4ef6879b9
md"""Which of these will show DeMorgan's law holds when both values are `false`:
"""

# ╔═╡ 16b7904a-53c0-11ec-3867-0fade81a24a0
let
	choices = ["`!(false && false) == (!false && !false)`",
	           "`!(false && false) == (false || false)`",
		   "`!(false && false) == (!false || !false)`"]
	ans = 3
	radioq(choices, ans)
end

# ╔═╡ 16b790b6-53c0-11ec-3bcf-15641fe03670
md"""###### Question
"""

# ╔═╡ 16b790f4-53c0-11ec-079f-bb5dc83d783b
md"""For floating point numbers there are two special values `Inf` and `NaN`. For which of these is the answer always `false`:
"""

# ╔═╡ 16b79d7e-53c0-11ec-2c1d-774ad3e6f70e
let
	choices = ["`Inf < 3.0` and `3.0 <= Inf`",
	           "`NaN < 3.0` and `3.0 <= NaN`"]
	ans = 2
	radioq(choices, ans)
end

# ╔═╡ 16b79db0-53c0-11ec-2250-87e7a78e3815
md"""###### Question
"""

# ╔═╡ 16b79de2-53c0-11ec-2fe9-f926f28cff84
md"""The IEEE 754 standard  is about floating point numbers, for which there are the special values `Inf`, `-Inf`, `NaN`, and, surprisingly, `-0.0` (as a floating point number and not `-0`, an integer). Here are 4 facts that seem reasonable:
"""

# ╔═╡ 16b7a2ec-53c0-11ec-3db2-9974525cc953
md"""  * Positive zero is equal but not greater than negative zero.
  * `Inf` is equal to itself and greater than everything else except `NaN`.
  * `-Inf` is equal to itself and less then everything else except `NaN`.
  * `NaN` is not equal to, not less than, and not greater than anything, including itself.
"""

# ╔═╡ 16b7a3c8-53c0-11ec-2384-5379a51f6a86
md"""Do all four seem to be the case within `Julia`? Find your answer by trial and error.
"""

# ╔═╡ 16b7a76a-53c0-11ec-1c64-8bc2e8859173
let
	yesnoq(true)
end

# ╔═╡ 16b7a7c4-53c0-11ec-0ac4-fb1895569e1c
md"""###### Question
"""

# ╔═╡ 16b7a86e-53c0-11ec-258e-b5af2915d790
md"""The `NaN` value is meant to signal an error in computation. `Julia` has value to indicate some data is missing or unavailable. This is `missing`. For `missing` values we have these computations:
"""

# ╔═╡ 16b7abb6-53c0-11ec-0483-75bb9a31af8d
true && missing, true || missing

# ╔═╡ 16b7acc4-53c0-11ec-13ea-f7bf6e16a873
md"""We see the value of `true || missing` is `true`. Why?
"""

# ╔═╡ 16b7c100-53c0-11ec-253c-a3d36357712c
let
	choices = ["""
	In the manual we can read that "In the expression `a || b`, the subexpression `b` is only evaluated if `a` evaluates to false." In this case `a` is `true` and so `a` is returned.
	""",
	"Since the second value is \"`missing`\", only the first is used. So `false || missing` would also be `false`"]
	ans = 1
	radioq(choices, ans)
end

# ╔═╡ 16b7c15a-53c0-11ec-04c1-b3a59a5934ac
md"""The value for `true && missing` is `missing`, not a boolean value. What happens?
"""

# ╔═╡ 16b7d924-53c0-11ec-1990-97caa40cc4d5
let
	choices = ["""
	In the manual we can read that "In the expression `a && b`, the subexpression `b` is only evaluated if `a` evaluates to true." In this case, `a` is `false` so `b` is evaluated and returned. As `b` is just `missing` that is the return value.
	""",
	"Since the second value is \"`missing`\" all such answers would be missing."]
	ans = 1
	radioq(choices, ans)
end

# ╔═╡ 16b7d9ce-53c0-11ec-2db0-51c38f37074c
HTML("""<div class="markdown"><blockquote>
<p><a href="../precalc/numbers_types.html">◅ previous</a>  <a href="../precalc/vectors.html">▻  next</a>  <a href="../misc/toc.html">⌂ table of contents</a>  <a href="https://github.com/jverzani/CalculusWithJulia.jl/edit/master/CwJ/precalc/logical_expressions.jmd">✏ suggest an edit</a></p>
</blockquote>
</div>""")

# ╔═╡ 16b7d9d8-53c0-11ec-3f70-294616560243
PlutoUI.TableOfContents()

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
CalculusWithJulia = "~0.0.10"
Plots = "~1.24.3"
PlutoUI = "~0.7.21"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.0"
manifest_format = "2.0"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "abb72771fd8895a7ebd83d5632dc4b989b022b5b"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.1.2"

[[deps.Adapt]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "84918055d15b3114ede17ac6a7182f68870c16f7"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "3.3.1"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[deps.ArrayInterface]]
deps = ["Compat", "IfElse", "LinearAlgebra", "Requires", "SparseArrays", "Static"]
git-tree-sha1 = "265b06e2b1f6a216e0e8f183d28e4d354eab3220"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "3.2.1"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "19a35467a82e236ff51bc17a3a44b69ef35185a2"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.8+0"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "f2202b55d816427cd385a9a4f3ffb226bee80f99"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.1+0"

[[deps.CalculusWithJulia]]
deps = ["Base64", "ColorTypes", "Contour", "DataFrames", "EllipsisNotation", "ForwardDiff", "HCubature", "IntervalSets", "JSON", "LaTeXStrings", "LinearAlgebra", "Markdown", "Mustache", "Pkg", "PlotUtils", "Pluto", "Random", "RecipesBase", "Reexport", "Requires", "SpecialFunctions", "Tectonic", "Test", "Weave"]
git-tree-sha1 = "7adfe1a4e3f52fc356dfa2b0b26457f0acf81aa2"
uuid = "a2e0e22d-7d4c-5312-9169-8b992201a882"
version = "0.0.10"

[[deps.ChainRulesCore]]
deps = ["Compat", "LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "f885e7e7c124f8c92650d61b9477b9ac2ee607dd"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "1.11.1"

[[deps.ChangesOfVariables]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "9a1d594397670492219635b35a3d830b04730d62"
uuid = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
version = "0.1.1"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "Random"]
git-tree-sha1 = "a851fec56cb73cfdf43762999ec72eff5b86882a"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.15.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "32a2b8af383f11cbb65803883837a149d10dfe8a"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.10.12"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "417b0ed7b8b838aa6ca0a87aadf1bb9eb111ce40"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.8"

[[deps.Combinatorics]]
git-tree-sha1 = "08c8b6831dc00bfea825826be0bc8336fc369860"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.2"

[[deps.CommonSubexpressions]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "7b8a93dba8af7e3b42fecabf646260105ac373f7"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.3.0"

[[deps.Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "SHA", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "dce3e3fea680869eaa0b774b2e8343e9ff442313"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "3.40.0"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"

[[deps.Configurations]]
deps = ["ExproniconLite", "OrderedCollections", "TOML"]
git-tree-sha1 = "b0dcafb34cfff977df79fc9927b70a9157a702ad"
uuid = "5218b696-f38b-4ac9-8b61-a12ec717816d"
version = "0.17.0"

[[deps.Contour]]
deps = ["StaticArrays"]
git-tree-sha1 = "9f02045d934dc030edad45944ea80dbd1f0ebea7"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.7"

[[deps.Crayons]]
git-tree-sha1 = "3f71217b538d7aaee0b69ab47d9b7724ca8afa0d"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.0.4"

[[deps.DataAPI]]
git-tree-sha1 = "cc70b17275652eb47bc9e5f81635981f13cea5c8"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.9.0"

[[deps.DataFrames]]
deps = ["Compat", "DataAPI", "Future", "InvertedIndices", "IteratorInterfaceExtensions", "LinearAlgebra", "Markdown", "Missings", "PooledArrays", "PrettyTables", "Printf", "REPL", "Reexport", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "d785f42445b63fc86caa08bb9a9351008be9b765"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "1.2.2"

[[deps.DataStructures]]
deps = ["Compat", "InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "7d9d316f04214f7efdbb6398d545446e246eff02"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.18.10"

[[deps.DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[deps.DiffResults]]
deps = ["StaticArrays"]
git-tree-sha1 = "c18e98cba888c6c25d1c3b048e4b3380ca956805"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "1.0.3"

[[deps.DiffRules]]
deps = ["LogExpFunctions", "NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "d8f468c5cd4d94e86816603f7d18ece910b4aaf1"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.5.0"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[deps.DocStringExtensions]]
deps = ["LibGit2"]
git-tree-sha1 = "b19534d1895d702889b219c382a6e18010797f0b"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.6"

[[deps.Downloads]]
deps = ["ArgTools", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[[deps.EarCut_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "3f3a2501fa7236e9b911e0f7a588c657e822bb6d"
uuid = "5ae413db-bbd1-5e63-b57d-d24a61df00f5"
version = "2.2.3+0"

[[deps.EllipsisNotation]]
deps = ["ArrayInterface"]
git-tree-sha1 = "3fe985505b4b667e1ae303c9ca64d181f09d5c05"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
version = "1.1.3"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b3bfd02e98aedfa5cf885665493c5598c350cd2f"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.10+0"

[[deps.ExproniconLite]]
git-tree-sha1 = "8b08cc88844e4d01db5a2405a08e9178e19e479e"
uuid = "55351af7-c7e9-48d6-89ff-24e801d99491"
version = "0.6.13"

[[deps.FFMPEG]]
deps = ["FFMPEG_jll"]
git-tree-sha1 = "b57e3acbe22f8484b4b5ff66a7499717fe1a9cc8"
uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
version = "0.4.1"

[[deps.FFMPEG_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "JLLWrappers", "LAME_jll", "Libdl", "Ogg_jll", "OpenSSL_jll", "Opus_jll", "Pkg", "Zlib_jll", "libass_jll", "libfdk_aac_jll", "libvorbis_jll", "x264_jll", "x265_jll"]
git-tree-sha1 = "d8a578692e3077ac998b50c0217dfd67f21d1e5f"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
version = "4.4.0+0"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "21efd19106a55620a188615da6d3d06cd7f6ee03"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.93+0"

[[deps.Formatting]]
deps = ["Printf"]
git-tree-sha1 = "8339d61043228fdd3eb658d86c926cb282ae72a8"
uuid = "59287772-0a20-5a39-b81b-1366585eb4c0"
version = "0.4.2"

[[deps.ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "LinearAlgebra", "LogExpFunctions", "NaNMath", "Preferences", "Printf", "Random", "SpecialFunctions", "StaticArrays"]
git-tree-sha1 = "6406b5112809c08b1baa5703ad274e1dded0652f"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.23"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.4+0"

[[deps.FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.10+0"

[[deps.Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[deps.FuzzyCompletions]]
deps = ["REPL"]
git-tree-sha1 = "2cc2791b324e8ed387a91d7226d17be754e9de61"
uuid = "fb4132e2-a121-4a70-b8a1-d5b831dcdcc2"
version = "0.4.3"

[[deps.GLFW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libglvnd_jll", "Pkg", "Xorg_libXcursor_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll"]
git-tree-sha1 = "0c603255764a1fa0b61752d2bec14cfbd18f7fe8"
uuid = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
version = "3.3.5+1"

[[deps.GR]]
deps = ["Base64", "DelimitedFiles", "GR_jll", "HTTP", "JSON", "Libdl", "LinearAlgebra", "Pkg", "Printf", "Random", "Serialization", "Sockets", "Test", "UUIDs"]
git-tree-sha1 = "30f2b340c2fff8410d89bfcdc9c0a6dd661ac5f7"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.62.1"

[[deps.GR_jll]]
deps = ["Artifacts", "Bzip2_jll", "Cairo_jll", "FFMPEG_jll", "Fontconfig_jll", "GLFW_jll", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pixman_jll", "Pkg", "Qt5Base_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "fd75fa3a2080109a2c0ec9864a6e14c60cca3866"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
version = "0.62.0+0"

[[deps.GeometryBasics]]
deps = ["EarCut_jll", "IterTools", "LinearAlgebra", "StaticArrays", "StructArrays", "Tables"]
git-tree-sha1 = "58bcdf5ebc057b085e58d95c138725628dd7453c"
uuid = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
version = "0.4.1"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "74ef6288d071f58033d54fd6708d4bc23a8b8972"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.68.3+1"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "344bf40dcab1073aca04aa0df4fb092f920e4011"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.14+0"

[[deps.Grisu]]
git-tree-sha1 = "53bb909d1151e57e2484c3d1b53e19552b887fb2"
uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe"
version = "1.0.2"

[[deps.HCubature]]
deps = ["Combinatorics", "DataStructures", "LinearAlgebra", "QuadGK", "StaticArrays"]
git-tree-sha1 = "134af3b940d1ca25b19bc9740948157cee7ff8fa"
uuid = "19dc6840-f33b-545b-b366-655c7e3ffd49"
version = "1.5.0"

[[deps.HTTP]]
deps = ["Base64", "Dates", "IniFile", "Logging", "MbedTLS", "NetworkOptions", "Sockets", "URIs"]
git-tree-sha1 = "0fa77022fe4b511826b39c894c90daf5fce3334a"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.9.17"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.Highlights]]
deps = ["DocStringExtensions", "InteractiveUtils", "REPL"]
git-tree-sha1 = "f823a2d04fb233d52812c8024a6d46d9581904a4"
uuid = "eafb193a-b7ab-5a9e-9068-77385905fa72"
version = "0.4.5"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "8d511d5b81240fc8e6802386302675bdf47737b9"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.4"

[[deps.HypertextLiteral]]
git-tree-sha1 = "2b078b5a615c6c0396c77810d92ee8c6f470d238"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.3"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "f7be53659ab06ddc986428d3a9dcc95f6fa6705a"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.2"

[[deps.IfElse]]
git-tree-sha1 = "debdd00ffef04665ccbb3e150747a77560e8fad1"
uuid = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
version = "0.1.1"

[[deps.IniFile]]
deps = ["Test"]
git-tree-sha1 = "098e4d2c533924c921f9f9847274f2ad89e018b8"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.5.0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.IntervalSets]]
deps = ["Dates", "EllipsisNotation", "Statistics"]
git-tree-sha1 = "3cc368af3f110a767ac786560045dceddfc16758"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.5.3"

[[deps.InverseFunctions]]
deps = ["Test"]
git-tree-sha1 = "a7254c0acd8e62f1ac75ad24d5db43f5f19f3c65"
uuid = "3587e190-3f89-42d0-90ee-14403ec27112"
version = "0.1.2"

[[deps.InvertedIndices]]
git-tree-sha1 = "bee5f1ef5bf65df56bdd2e40447590b272a5471f"
uuid = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
version = "1.1.0"

[[deps.IrrationalConstants]]
git-tree-sha1 = "7fd44fd4ff43fc60815f8e764c0f352b83c49151"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.1.1"

[[deps.IterTools]]
git-tree-sha1 = "05110a2ab1fc5f932622ffea2a003221f4782c18"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.3.0"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "642a199af8b68253517b80bd3bfd17eb4e84df6e"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.3.0"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "8076680b162ada2a031f707ac7b4953e30667a37"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.2"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "d735490ac75c5cb9f1b00d8b5509c11984dc6943"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.1.0+0"

[[deps.LAME_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "f6250b16881adf048549549fba48b1161acdac8c"
uuid = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
version = "3.100.1+0"

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e5b909bcf985c5e2605737d2ce278ed791b89be6"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.1+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"

[[deps.Latexify]]
deps = ["Formatting", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "Printf", "Requires"]
git-tree-sha1 = "a8f4f279b6fa3c3c4f1adadd78a621b13a506bce"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.15.9"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+1"

[[deps.Libgcrypt_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "64613c82a59c120435c067c2b809fc61cf5166ae"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.7+0"

[[deps.Libglvnd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "7739f837d6447403596a75d19ed01fd08d6f56bf"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.3.0+3"

[[deps.Libgpg_error_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c333716e46366857753e273ce6a69ee0945a6db9"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.42.0+0"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "42b62845d70a619f063a7da093d995ec8e15e778"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.1+1"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.35.0+0"

[[deps.Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "340e257aada13f95f98ee352d316c3bed37c8ab9"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.3.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.36.0+0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[deps.LogExpFunctions]]
deps = ["ChainRulesCore", "ChangesOfVariables", "DocStringExtensions", "InverseFunctions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "be9eef9f9d78cecb6f262f3c10da151a6c5ab827"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.5"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "3d3e902b31198a27340d0bf00d6ac452866021cf"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.9"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "Random", "Sockets"]
git-tree-sha1 = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.0.3"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[deps.Measures]]
git-tree-sha1 = "e498ddeee6f9fdb4551ce855a46f54dbd900245f"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.3.1"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "bf210ce90b6c9eed32d25dbcae1ebc565df2687f"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.0.2"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[deps.MsgPack]]
deps = ["Serialization"]
git-tree-sha1 = "a8cbf066b54d793b9a48c5daa5d586cf2b5bd43d"
uuid = "99f44e22-a591-53d1-9472-aa23ef4bd671"
version = "1.1.0"

[[deps.Mustache]]
deps = ["Printf", "Tables"]
git-tree-sha1 = "21d7a05c3b94bcf45af67beccab4f2a1f4a3c30a"
uuid = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
version = "1.0.12"

[[deps.NaNMath]]
git-tree-sha1 = "bfe47e760d60b82b66b61d2d44128b62e3a369fb"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.5"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"

[[deps.Ogg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7937eda4681660b4d6aeeecc2f7e1c81c8ee4e2f"
uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051"
version = "1.3.5+0"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"

[[deps.OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "15003dcb7d8db3c6c857fda14891a539a8f2705a"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.10+0"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "13652491f6856acfd2db29360e1bbcd4565d04f1"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.5+0"

[[deps.Opus_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "51a08fb14ec28da2ec7a927c4337e4332c2a4720"
uuid = "91d4177d-7536-5919-b921-800302f37372"
version = "1.3.2+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.4.1"

[[deps.PCRE_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b2a7af664e098055a7529ad1a900ded962bca488"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.44.0+0"

[[deps.Parsers]]
deps = ["Dates"]
git-tree-sha1 = "ae4bbcadb2906ccc085cf52ac286dc1377dceccc"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.1.2"

[[deps.Pixman_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4f5d02549a10e20780a24fce72bea96b6329e29"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.40.1+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[deps.PlotThemes]]
deps = ["PlotUtils", "Requires", "Statistics"]
git-tree-sha1 = "a3a964ce9dc7898193536002a6dd892b1b5a6f1d"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "2.0.1"

[[deps.PlotUtils]]
deps = ["ColorSchemes", "Colors", "Dates", "Printf", "Random", "Reexport", "Statistics"]
git-tree-sha1 = "b084324b4af5a438cd63619fd006614b3b20b87b"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "1.0.15"

[[deps.Plots]]
deps = ["Base64", "Contour", "Dates", "Downloads", "FFMPEG", "FixedPointNumbers", "GR", "GeometryBasics", "JSON", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "Requires", "Scratch", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs", "UnicodeFun"]
git-tree-sha1 = "d73736030a094e8d24fdf3629ae980217bf1d59d"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.24.3"

[[deps.Pluto]]
deps = ["Base64", "Configurations", "Dates", "Distributed", "FileWatching", "FuzzyCompletions", "HTTP", "InteractiveUtils", "Logging", "Markdown", "MsgPack", "Pkg", "REPL", "Sockets", "TableIOInterface", "Tables", "UUIDs"]
git-tree-sha1 = "a5b3fee95de0c0a324bab53a03911395936d15d9"
uuid = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
version = "0.17.2"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "Dates", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "Markdown", "Random", "Reexport", "UUIDs"]
git-tree-sha1 = "b68904528fd538f1cb6a3fbc44d2abdc498f9e8e"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.21"

[[deps.PooledArrays]]
deps = ["DataAPI", "Future"]
git-tree-sha1 = "db3a23166af8aebf4db5ef87ac5b00d36eb771e2"
uuid = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
version = "1.4.0"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "00cfd92944ca9c760982747e9a1d0d5d86ab1e5a"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.2.2"

[[deps.PrettyTables]]
deps = ["Crayons", "Formatting", "Markdown", "Reexport", "Tables"]
git-tree-sha1 = "d940010be611ee9d67064fe559edbb305f8cc0eb"
uuid = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
version = "1.2.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Qt5Base_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Fontconfig_jll", "Glib_jll", "JLLWrappers", "Libdl", "Libglvnd_jll", "OpenSSL_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libxcb_jll", "Xorg_xcb_util_image_jll", "Xorg_xcb_util_keysyms_jll", "Xorg_xcb_util_renderutil_jll", "Xorg_xcb_util_wm_jll", "Zlib_jll", "xkbcommon_jll"]
git-tree-sha1 = "ad368663a5e20dbb8d6dc2fddeefe4dae0781ae8"
uuid = "ea2cea3b-5b76-57ae-a6ef-0a8af62496e1"
version = "5.15.3+0"

[[deps.QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "78aadffb3efd2155af139781b8a8df1ef279ea39"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.4.2"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.RecipesBase]]
git-tree-sha1 = "6bf3f380ff52ce0832ddd3a2a7b9538ed1bcca7d"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.2.1"

[[deps.RecipesPipeline]]
deps = ["Dates", "NaNMath", "PlotUtils", "RecipesBase"]
git-tree-sha1 = "7ad0dfa8d03b7bcf8c597f59f5292801730c55b8"
uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c"
version = "0.4.1"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.RelocatableFolders]]
deps = ["SHA", "Scratch"]
git-tree-sha1 = "cdbd3b1338c72ce29d9584fdbe9e9b70eeb5adca"
uuid = "05181044-ff0b-4ac5-8273-598c1e38db00"
version = "0.1.3"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "4036a3bd08ac7e968e27c203d45f5fff15020621"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.1.3"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "0b4b7f1393cff97c33891da2a0bf69c6ed241fda"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.1.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[deps.Showoff]]
deps = ["Dates", "Grisu"]
git-tree-sha1 = "91eddf657aca81df9ae6ceb20b959ae5653ad1de"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "1.0.3"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "b3363d7460f7d098ca0912c69b082f75625d7508"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.0.1"

[[deps.SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.SpecialFunctions]]
deps = ["ChainRulesCore", "IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "f0bccf98e16759818ffc5d97ac3ebf87eb950150"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "1.8.1"

[[deps.Static]]
deps = ["IfElse"]
git-tree-sha1 = "e7bc80dc93f50857a5d1e3c8121495852f407e6a"
uuid = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
version = "0.4.0"

[[deps.StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "3c76dde64d03699e074ac02eb2e8ba8254d428da"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.2.13"

[[deps.Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[deps.StatsAPI]]
git-tree-sha1 = "0f2aa8e32d511f758a2ce49208181f7733a0936a"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.1.0"

[[deps.StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "2bb0cb32026a66037360606510fca5984ccc6b75"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.13"

[[deps.StringEncodings]]
deps = ["Libiconv_jll"]
git-tree-sha1 = "50ccd5ddb00d19392577902f0079267a72c5ab04"
uuid = "69024149-9ee7-55f6-a4c4-859efe599b68"
version = "0.3.5"

[[deps.StructArrays]]
deps = ["Adapt", "DataAPI", "StaticArrays", "Tables"]
git-tree-sha1 = "2ce41e0d042c60ecd131e9fb7154a3bfadbf50d3"
uuid = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
version = "0.6.3"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[deps.TableIOInterface]]
git-tree-sha1 = "9a0d3ab8afd14f33a35af7391491ff3104401a35"
uuid = "d1efa939-5518-4425-949f-ab857e148477"
version = "0.1.6"

[[deps.TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "c06b2f539df1c6efa794486abfb6ed2022561a39"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

[[deps.Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "LinearAlgebra", "TableTraits", "Test"]
git-tree-sha1 = "fed34d0e71b91734bf0a7e10eb1bb05296ddbcd0"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.6.0"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[deps.Tectonic]]
deps = ["Pkg"]
git-tree-sha1 = "e3e5e7dfbe3b7d9ff767264f84e5eca487e586cb"
uuid = "9ac5f52a-99c6-489f-af81-462ef484790f"
version = "0.2.0"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.URIs]]
git-tree-sha1 = "97bbe755a53fe859669cd907f2d96aee8d2c1355"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.3.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.UnicodeFun]]
deps = ["REPL"]
git-tree-sha1 = "53915e50200959667e78a92a418594b428dffddf"
uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1"
version = "0.4.1"

[[deps.Wayland_jll]]
deps = ["Artifacts", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "3e61f0b86f90dacb0bc0e73a0c5a83f6a8636e23"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.19.0+0"

[[deps.Wayland_protocols_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "66d72dc6fcc86352f01676e8f0f698562e60510f"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.23.0+0"

[[deps.Weave]]
deps = ["Base64", "Dates", "Highlights", "JSON", "Markdown", "Mustache", "Pkg", "Printf", "REPL", "RelocatableFolders", "Requires", "Serialization", "YAML"]
git-tree-sha1 = "d62575dcea5aeb2bfdfe3b382d145b65975b5265"
uuid = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
version = "0.10.10"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "1acf5bdf07aa0907e0a37d3718bb88d4b687b74a"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.12+0"

[[deps.XSLT_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgcrypt_jll", "Libgpg_error_jll", "Libiconv_jll", "Pkg", "XML2_jll", "Zlib_jll"]
git-tree-sha1 = "91844873c4085240b95e795f692c4cec4d805f8a"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.34+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "5be649d550f3f4b95308bf0183b82e2582876527"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+4"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4e490d5c960c314f33885790ed410ff3a94ce67e"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+4"

[[deps.Xorg_libXcursor_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "12e0eb3bc634fa2080c1c37fccf56f7c22989afd"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+4"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fe47bd2247248125c428978740e18a681372dd4"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+4"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "b7c0aa8c376b31e4852b360222848637f481f8c3"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+4"

[[deps.Xorg_libXfixes_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "0e0dc7431e7a0587559f9294aeec269471c991a4"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+4"

[[deps.Xorg_libXi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "89b52bc2160aadc84d707093930ef0bffa641246"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+4"

[[deps.Xorg_libXinerama_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "26be8b1c342929259317d8b9f7b53bf2bb73b123"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+4"

[[deps.Xorg_libXrandr_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "34cea83cb726fb58f325887bf0612c6b3fb17631"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+4"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+4"

[[deps.Xorg_libpthread_stubs_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+3"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "daf17f441228e7a3833846cd048892861cff16d6"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[[deps.Xorg_libxkbfile_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "926af861744212db0eb001d9e40b5d16292080b2"
uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a"
version = "1.1.0+4"

[[deps.Xorg_xcb_util_image_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "0fab0a40349ba1cba2c1da699243396ff8e94b97"
uuid = "12413925-8142-5f55-bb0e-6d7ca50bb09b"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll"]
git-tree-sha1 = "e7fd7b2881fa2eaa72717420894d3938177862d1"
uuid = "2def613f-5ad1-5310-b15b-b15d46f528f5"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_keysyms_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "d1151e2c45a544f32441a567d1690e701ec89b00"
uuid = "975044d2-76e6-5fbe-bf08-97ce7c6574c7"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_renderutil_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "dfd7a8f38d4613b6a575253b3174dd991ca6183e"
uuid = "0d47668e-0667-5a69-a72c-f761630bfb7e"
version = "0.3.9+1"

[[deps.Xorg_xcb_util_wm_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "e78d10aab01a4a154142c5006ed44fd9e8e31b67"
uuid = "c22f9ab0-d5fe-5066-847c-f4bb1cd4e361"
version = "0.4.1+1"

[[deps.Xorg_xkbcomp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxkbfile_jll"]
git-tree-sha1 = "4bcbf660f6c2e714f87e960a171b119d06ee163b"
uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4"
version = "1.4.2+4"

[[deps.Xorg_xkeyboard_config_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xkbcomp_jll"]
git-tree-sha1 = "5c8424f8a67c3f2209646d4425f3d415fee5931d"
uuid = "33bec58e-1273-512f-9401-5d533626f822"
version = "2.27.0+4"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79c31e7844f6ecf779705fbc12146eb190b7d845"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+3"

[[deps.YAML]]
deps = ["Base64", "Dates", "Printf", "StringEncodings"]
git-tree-sha1 = "3c6e8b9f5cdaaa21340f841653942e1a6b6561e5"
uuid = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
version = "0.4.7"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[deps.Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "cc4bf3fdde8b7e3e9fa0351bdeedba1cf3b7f6e6"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.5.0+0"

[[deps.libass_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "HarfBuzz_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "5982a94fcba20f02f42ace44b9894ee2b140fe47"
uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
version = "0.15.1+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl", "OpenBLAS_jll"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"

[[deps.libfdk_aac_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "daacc84a041563f965be61859a36e17c4e4fcd55"
uuid = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
version = "2.0.2+0"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.38+0"

[[deps.libvorbis_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "c45f4e40e7aafe9d086379e5578947ec8b95a8fb"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.7+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[[deps.x264_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fea590b89e6ec504593146bf8b988b2c00922b2"
uuid = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
version = "2021.5.5+0"

[[deps.x265_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "ee567a171cce03570d77ad3a43e90218e38937a9"
uuid = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
version = "3.5.0+0"

[[deps.xkbcommon_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Wayland_jll", "Wayland_protocols_jll", "Xorg_libxcb_jll", "Xorg_xkeyboard_config_jll"]
git-tree-sha1 = "ece2350174195bb31de1a63bea3a41ae1aa593b6"
uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
version = "0.9.1+5"
"""

# ╔═╡ Cell order:
# ╟─16b7d9ba-53c0-11ec-2db3-3bcd6a3009eb
# ╟─16aec514-53c0-11ec-2a33-871e1c8bf520
# ╟─16aec73a-53c0-11ec-161b-dbdf0de58e89
# ╠═16af3316-53c0-11ec-3a0f-618d61ab9384
# ╟─16af65e6-53c0-11ec-31ab-dfb9afb3123d
# ╟─16af68b6-53c0-11ec-33ca-97033b256f68
# ╟─16af6d84-53c0-11ec-0aee-817231a7b384
# ╟─16af6fb4-53c0-11ec-1ac9-6faf64e7cce1
# ╠═16b14bf4-53c0-11ec-1fc7-2147aa8d6010
# ╟─16b1514e-53c0-11ec-060e-079db87a9554
# ╟─16b1524a-53c0-11ec-0921-e119ec5298b7
# ╟─16b1da30-53c0-11ec-0c56-9507494ff28b
# ╟─16b1dbc6-53c0-11ec-058a-5d1ffb1eb25d
# ╠═16b1e8d4-53c0-11ec-1274-5f666d58ebf8
# ╟─16b1ea48-53c0-11ec-093c-e993a8056c40
# ╟─16b1eb36-53c0-11ec-1c6f-c9785769afe1
# ╟─16b1ebfe-53c0-11ec-1e49-85bbe1375432
# ╟─16b1ed02-53c0-11ec-1e9c-db0fad8b3ccf
# ╟─16b1eddc-53c0-11ec-0200-3747fa27aef7
# ╠═16b2c132-53c0-11ec-23df-2ded88db8924
# ╟─16b2c29a-53c0-11ec-2306-c7797b538c6a
# ╠═16b33644-53c0-11ec-14d3-8963e015c5c9
# ╟─16b336d0-53c0-11ec-37e9-51475119e239
# ╟─16b3d554-53c0-11ec-2edf-577ee8153bdd
# ╟─16b3d694-53c0-11ec-03c9-817787e93f5a
# ╟─16b3d6d2-53c0-11ec-0ba6-dfcaf8cdba76
# ╟─16b40600-53c0-11ec-04d4-c9737b321004
# ╠═16b42430-53c0-11ec-010e-3be296410095
# ╟─16b424be-53c0-11ec-3b61-dd69b2699f15
# ╟─16b425e0-53c0-11ec-0f4d-db45b620abc9
# ╠═16b43e20-53c0-11ec-1744-01daacfbabe4
# ╟─16b43f44-53c0-11ec-2b70-0fbc6926fa69
# ╟─16b43fba-53c0-11ec-15d1-adc988e201bf
# ╟─16b44052-53c0-11ec-0bf0-5d297a617aa8
# ╠═16b44746-53c0-11ec-1fdf-092e7aeba1e6
# ╟─16b4476e-53c0-11ec-1ffb-5d2d87aedbaf
# ╟─16b457fe-53c0-11ec-056f-1d0f1b25676a
# ╟─16b45874-53c0-11ec-2c45-6349cc541cf8
# ╟─16b45a92-53c0-11ec-047f-b3a57613deaf
# ╟─16b4727a-53c0-11ec-2900-0d05a16c4aa4
# ╠═16b4bbd6-53c0-11ec-1206-8fc32484b780
# ╟─16b4bd70-53c0-11ec-2e54-03c73d5f9761
# ╟─16b4c108-53c0-11ec-2962-a31a5fa47290
# ╟─16b4c1a8-53c0-11ec-19b2-4599ee730808
# ╠═16b4cab8-53c0-11ec-1b47-0d97e23c8867
# ╟─16b4cbb2-53c0-11ec-385f-4b813f3dac2f
# ╟─16b4cc52-53c0-11ec-3051-3d2d54d06445
# ╠═16b4eb24-53c0-11ec-27f2-576bb9dcbbbd
# ╟─16b4ebec-53c0-11ec-2128-5ba4a40cd7ed
# ╟─16b4ec5a-53c0-11ec-2755-511aac0eddc1
# ╟─16b4ec8c-53c0-11ec-2911-3df115a82e09
# ╟─16b4ece6-53c0-11ec-186e-4b7681eebc8a
# ╟─16b515ae-53c0-11ec-2dd8-ff6885c9709b
# ╟─16b51612-53c0-11ec-1763-d5606514ed94
# ╠═16b51d24-53c0-11ec-1b12-5dd6da7d0200
# ╟─16b51dd8-53c0-11ec-0673-851c948f89de
# ╠═16b524cc-53c0-11ec-247a-0b9bebf1d337
# ╟─16b5261e-53c0-11ec-1c0c-e7ae3b21cd3d
# ╟─16b527e2-53c0-11ec-2db1-915608f747c9
# ╟─16b529b8-53c0-11ec-03e8-19ef164fac03
# ╟─16b529e0-53c0-11ec-3807-89c06252e092
# ╠═16b57b3e-53c0-11ec-13af-99bad9a90732
# ╟─16b57cec-53c0-11ec-14e3-c91ea4f5e173
# ╠═16b58714-53c0-11ec-18cc-0755a70e5fd4
# ╟─16b58804-53c0-11ec-1fb4-1be5cb49ef4f
# ╟─16b58c50-53c0-11ec-2dd4-894944e205ff
# ╟─16b58d72-53c0-11ec-2407-09540dabd319
# ╠═16b596a0-53c0-11ec-206b-11d0acd65780
# ╟─16b59740-53c0-11ec-0c28-974b7a6e527e
# ╟─16b5995c-53c0-11ec-3af2-4902a2e40ec8
# ╠═16b5a296-53c0-11ec-1b8c-b9f6906fdee1
# ╟─16b5a348-53c0-11ec-3293-9d110d958530
# ╠═16b5aaaa-53c0-11ec-2c04-6f41f3927e58
# ╟─16b5ab4a-53c0-11ec-1eb5-9f2cdef53688
# ╟─16b5acd0-53c0-11ec-2d2a-37262767f9d5
# ╟─16b5ad5c-53c0-11ec-190e-cba71689a082
# ╠═16b5d32c-53c0-11ec-1510-db07f8cb1117
# ╟─16b5d438-53c0-11ec-3125-1fc0873562d7
# ╟─16b5d4dc-53c0-11ec-3278-d32c1e7b5aeb
# ╟─16b5d502-53c0-11ec-327a-add85c50c600
# ╟─16b5d5c0-53c0-11ec-0237-ad8e54713641
# ╠═16b5e362-53c0-11ec-2a79-5f2bccafc494
# ╟─16b5e3da-53c0-11ec-1012-31c1b73090fb
# ╟─16b5e4ac-53c0-11ec-0383-f94b93235864
# ╠═16b5e984-53c0-11ec-37d5-6fd0bcd54fdb
# ╟─16b5ea6a-53c0-11ec-15cf-9d0dee5bc1d2
# ╟─16b5eba0-53c0-11ec-2f90-69a13ca5af4b
# ╠═16b62c6e-53c0-11ec-1244-6b86388df3b0
# ╟─16b62d48-53c0-11ec-05a0-a9946fc1ff88
# ╟─16b62d68-53c0-11ec-0f04-39385e939e98
# ╟─16b6458c-53c0-11ec-34e0-ddf6f8387240
# ╟─16b64672-53c0-11ec-3c51-cba776096f14
# ╟─16b65b6c-53c0-11ec-002b-15827bab88fc
# ╟─16b65bb2-53c0-11ec-1979-39195b7571f0
# ╟─16b65c66-53c0-11ec-0fae-930546634c96
# ╟─16b666b6-53c0-11ec-0334-1f50d36619a6
# ╟─16b666f2-53c0-11ec-1dc5-4da83ee67bdc
# ╟─16b66742-53c0-11ec-0617-b74a1fdfbf0d
# ╟─16b6866e-53c0-11ec-3666-d99f4fa29326
# ╟─16b686bc-53c0-11ec-0b70-95353cd190a2
# ╟─16b6881c-53c0-11ec-21c2-7d10344a9792
# ╟─16b69b54-53c0-11ec-26da-8b7d999b986c
# ╟─16b69b86-53c0-11ec-1b73-efaa07298ed9
# ╟─16b69d4a-53c0-11ec-09fd-874cfe9ddaed
# ╠═16b6a108-53c0-11ec-0b9f-05d81d4b9cbe
# ╟─16b6a1d0-53c0-11ec-0cd2-85555bdf8dbc
# ╟─16b6c7b6-53c0-11ec-1816-4d0bd713ff62
# ╟─16b6c868-53c0-11ec-1634-45613bb43ecc
# ╟─16b6c8ae-53c0-11ec-1ba7-315d5d27ca36
# ╟─16b702b0-53c0-11ec-01db-15319cf063c3
# ╟─16b7030a-53c0-11ec-2e88-a9f03e889aa2
# ╟─16b704a4-53c0-11ec-068f-e9a802d41913
# ╟─16b712fa-53c0-11ec-27b0-9fadea96c0de
# ╟─16b713b8-53c0-11ec-05c5-55c136a8b81f
# ╟─16b7144e-53c0-11ec-102c-6d7d6ce98af8
# ╟─16b72074-53c0-11ec-1a62-990af43d7d97
# ╟─16b7210a-53c0-11ec-3ac9-c1ebee56ba42
# ╟─16b72150-53c0-11ec-33d0-7bf098b54362
# ╟─16b74144-53c0-11ec-09a7-a3d5e65a9fe8
# ╟─16b74180-53c0-11ec-0063-5fc4fef76353
# ╟─16b74202-53c0-11ec-0b87-695b6d983c83
# ╟─16b74f7c-53c0-11ec-338f-eb4e1d892634
# ╟─16b75044-53c0-11ec-3045-1d2c5ced623e
# ╟─16b750ee-53c0-11ec-39d0-ed51879c0ebf
# ╟─16b751c8-53c0-11ec-3705-97b4ef6036c1
# ╟─16b75210-53c0-11ec-1b29-9b6b7659fca4
# ╟─16b757da-53c0-11ec-195a-a7a6feddec66
# ╟─16b75814-53c0-11ec-237b-556342a6ff93
# ╟─16b758c8-53c0-11ec-1b13-292422eaa548
# ╟─16b75e90-53c0-11ec-2058-b95477b0893c
# ╟─16b75ecc-53c0-11ec-26a6-1b25783e16d0
# ╟─16b7600c-53c0-11ec-08f6-8db4ef6879b9
# ╟─16b7904a-53c0-11ec-3867-0fade81a24a0
# ╟─16b790b6-53c0-11ec-3bcf-15641fe03670
# ╟─16b790f4-53c0-11ec-079f-bb5dc83d783b
# ╟─16b79d7e-53c0-11ec-2c1d-774ad3e6f70e
# ╟─16b79db0-53c0-11ec-2250-87e7a78e3815
# ╟─16b79de2-53c0-11ec-2fe9-f926f28cff84
# ╟─16b7a2ec-53c0-11ec-3db2-9974525cc953
# ╟─16b7a3c8-53c0-11ec-2384-5379a51f6a86
# ╟─16b7a76a-53c0-11ec-1c64-8bc2e8859173
# ╟─16b7a7c4-53c0-11ec-0ac4-fb1895569e1c
# ╟─16b7a86e-53c0-11ec-258e-b5af2915d790
# ╠═16b7abb6-53c0-11ec-0483-75bb9a31af8d
# ╟─16b7acc4-53c0-11ec-13ea-f7bf6e16a873
# ╟─16b7c100-53c0-11ec-253c-a3d36357712c
# ╟─16b7c15a-53c0-11ec-04c1-b3a59a5934ac
# ╟─16b7d924-53c0-11ec-1990-97caa40cc4d5
# ╟─16b7d9ce-53c0-11ec-2db0-51c38f37074c
# ╟─16b7d9d8-53c0-11ec-1155-7f4d8dc916a4
# ╟─16b7d9d8-53c0-11ec-3f70-294616560243
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
